import type { FighterIdValue } from '../../types/game.ts'
import type { OscWave } from '../SfxTypes.ts'

export interface AudioSignature {
  id: FighterIdValue
  primary: string
  secondary: string
  energy: string
  impact: string
  movement: string
  defensive: string
  weight: number
  wave: OscWave
  subWave: OscWave
  baseHz: number
  grit: number
  filterHz: number
  brightness: number
  stepHz: number
  dashHz: number
  landHz: number
  pascal: string
}

export const SIGNATURES: Record<FighterIdValue, AudioSignature> = {
  rimuru: {
    id: 'rimuru',
    pascal: 'Rimuru',
    primary: 'Great Sage system ticks + clean slime magic',
    secondary: 'Water-filtered whoosh, never generic splash spam',
    energy: 'skill-magic / unique skills',
    impact: 'glassy magic burst',
    movement: 'light, wet-air slide',
    defensive: 'barrier shimmer',
    weight: 0.82,
    wave: 'sine',
    subWave: 'triangle',
    baseHz: 392,
    grit: 0.12,
    filterHz: 2400,
    brightness: 1.25,
    stepHz: 420,
    dashHz: 680,
    landHz: 180,
  },
  milim: {
    id: 'milim',
    pascal: 'Milim',
    primary: 'Explosive dragon ki, childish sparkle over brute force',
    secondary: 'Fast punches that still hit like a True Dragon',
    energy: 'draconic + raw magic',
    impact: 'body explosion',
    movement: 'light-fast, heavy landing',
    defensive: 'pride snarl',
    weight: 1.05,
    wave: 'sawtooth',
    subWave: 'square',
    baseHz: 196,
    grit: 0.45,
    filterHz: 1600,
    brightness: 1.1,
    stepHz: 300,
    dashHz: 520,
    landHz: 90,
  },
  diablo: {
    id: 'diablo',
    pascal: 'Diablo',
    primary: 'Elegant demonic distortion, low FM, never cartoon evil',
    secondary: 'Velvet bass + reality crease',
    energy: 'primordial demon magic',
    impact: 'void crush',
    movement: 'silent glide, cloth',
    defensive: 'polite barrier click',
    weight: 0.88,
    wave: 'sine',
    subWave: 'sawtooth',
    baseHz: 98,
    grit: 0.22,
    filterHz: 900,
    brightness: 0.7,
    stepHz: 210,
    dashHz: 140,
    landHz: 70,
  },
  benimaru: {
    id: 'benimaru',
    pascal: 'Benimaru',
    primary: 'Katana steel + ogre flame, military snap',
    secondary: 'Combustion whoosh, not campfire',
    energy: 'black/red flame ki',
    impact: 'searing slash',
    movement: 'sharp steps, cloth-armor',
    defensive: 'blade parry ring',
    weight: 0.96,
    wave: 'square',
    subWave: 'sawtooth',
    baseHz: 220,
    grit: 0.38,
    filterHz: 1800,
    brightness: 1.15,
    stepHz: 340,
    dashHz: 640,
    landHz: 130,
  },
  shion: {
    id: 'shion',
    pascal: 'Shion',
    primary: 'Massive cleaver mass, kitchen-steel violence',
    secondary: 'Body power, delayed boom',
    energy: 'physical ogre ki',
    impact: 'heavy blunt + metal',
    movement: 'heavy boots',
    defensive: 'armor clang',
    weight: 1.28,
    wave: 'triangle',
    subWave: 'sawtooth',
    baseHz: 73,
    grit: 0.55,
    filterHz: 700,
    brightness: 0.65,
    stepHz: 140,
    dashHz: 180,
    landHz: 48,
  },
  veldora: {
    id: 'veldora',
    pascal: 'Veldora',
    primary: 'Storm Dragon mass: thunder body + gale',
    secondary: 'Roar in the sub-bass, not anime scream',
    energy: 'storm / wind / lightning of a True Dragon',
    impact: 'cataclysm',
    movement: 'ground-shaking steps',
    defensive: 'scale scrape',
    weight: 1.45,
    wave: 'sawtooth',
    subWave: 'sine',
    baseHz: 55,
    grit: 0.62,
    filterHz: 600,
    brightness: 0.85,
    stepHz: 90,
    dashHz: 110,
    landHz: 36,
  },
  hinata: {
    id: 'hinata',
    pascal: 'Hinata',
    primary: 'Holy knight precision — short, bright, surgical',
    secondary: 'Spirit light, Melt Slash hiss',
    energy: 'holy / spiritual',
    impact: 'light-blade',
    movement: 'light boots, no scrape',
    defensive: 'faith barrier chime',
    weight: 0.8,
    wave: 'triangle',
    subWave: 'sine',
    baseHz: 523,
    grit: 0.08,
    filterHz: 3200,
    brightness: 1.4,
    stepHz: 480,
    dashHz: 900,
    landHz: 220,
  },
  guy: {
    id: 'guy',
    pascal: 'Guy',
    primary: 'Primordial control: cold, sophisticated, crushing',
    secondary: 'Ice-demon elegance, not chaotic dark',
    energy: 'advanced demonic magic',
    impact: 'absolute freeze-crush',
    movement: 'measured, heavy-grace',
    defensive: 'pride wall',
    weight: 1.12,
    wave: 'sine',
    subWave: 'triangle',
    baseHz: 82,
    grit: 0.18,
    filterHz: 1100,
    brightness: 0.75,
    stepHz: 160,
    dashHz: 200,
    landHz: 55,
  },
  shuna: {
    id: 'shuna',
    pascal: 'Shuna',
    primary: 'Priestess onmyou: choir-like holy flame',
    secondary: 'Paper charm / ofuda flick',
    energy: 'holy analysis magic',
    impact: 'sacred flare',
    movement: 'kimono rustle, light',
    defensive: 'temple bell barrier',
    weight: 0.74,
    wave: 'sine',
    subWave: 'triangle',
    baseHz: 587,
    grit: 0.06,
    filterHz: 2800,
    brightness: 1.35,
    stepHz: 500,
    dashHz: 760,
    landHz: 240,
  },
  souei: {
    id: 'souei',
    pascal: 'Souei',
    primary: 'Dry shadow: short, muted, assassin-quiet',
    secondary: 'Clone flutter, kunai tick',
    energy: 'shadow / stealth ki',
    impact: 'pierce, not boom',
    movement: 'almost silent',
    defensive: 'smoke vanish',
    weight: 0.7,
    wave: 'square',
    subWave: 'triangle',
    baseHz: 185,
    grit: 0.15,
    filterHz: 1400,
    brightness: 0.55,
    stepHz: 260,
    dashHz: 420,
    landHz: 200,
  },
  hakurou: {
    id: 'hakurou',
    pascal: 'Hakurou',
    primary: 'Iai: silence then steel, old-master restraint',
    secondary: 'Scabbard wood, moon-bright cut',
    energy: 'sword ki, no element spam',
    impact: 'single clean cut',
    movement: 'geta / light martial',
    defensive: 'blade catch',
    weight: 0.9,
    wave: 'triangle',
    subWave: 'sine',
    baseHz: 311,
    grit: 0.1,
    filterHz: 2600,
    brightness: 1.2,
    stepHz: 360,
    dashHz: 780,
    landHz: 170,
  },
}

export function signatureOf(id: FighterIdValue): AudioSignature {
  return SIGNATURES[id]
}
