import { StorySource, type StoryArcDef } from '../types.ts'

/** Colonne vertébrale LN jusqu'à Walpurgis. Chaque arc a une mission jouable. */
export const STORY_ARCS: readonly StoryArcDef[] = [
  {
    id: 'prologue',
    title: 'Réincarnation',
    chronology: 1,
    summary: 'Satoru Mikami meurt à Tokyo et se réveille slime. Great Sage s\'éveille.',
    source: StorySource.LN,
  },
  {
    id: 'sealed_cave',
    title: 'Grotte Scellée',
    chronology: 2,
    summary: 'Rimuru explore la caverne magique, analyse, puis rencontre Veldora scellé.',
    source: StorySource.LN,
    location: 'sealed_cave',
  },
  {
    id: 'goblins',
    title: 'Village gobelin',
    chronology: 3,
    summary: 'Sortie de la grotte. Gobelins de Jura, attaque des loups, nom de Ranga.',
    source: StorySource.LN,
    location: 'jura_forest',
  },
  {
    id: 'ogres',
    title: 'Ogres survivants',
    chronology: 4,
    summary: 'Benimaru, Shion, Shuna, Souei, Hakurou rejoignent Rimuru après le massacre orc.',
    source: StorySource.LN,
    location: 'jura_forest',
  },
  {
    id: 'orcs',
    title: 'Seigneur Orc',
    chronology: 5,
    summary: 'Guerre des Orcs, Geld, famine magique, bataille pour Jura.',
    source: StorySource.LN,
    location: 'jura_forest',
  },
  {
    id: 'shizu',
    title: 'Shizu',
    chronology: 6,
    summary: 'Shizu et Ifrit. Rimuru n\'a l\'apparence humaine actuelle qu\'après l\'absorption.',
    source: StorySource.LN,
    location: 'jura_forest',
  },
  {
    id: 'tempest',
    title: 'Fédération Tempest',
    chronology: 7,
    summary: 'Village, noms, alliances Dwargon/Blumund, fondation de Tempest.',
    source: StorySource.LN,
    location: 'tempest_city',
  },
  {
    id: 'charybdis',
    title: 'Charybdis',
    chronology: 8,
    summary: 'Phobio, invocation de Charybdis, défense de Tempest avec Eurazania.',
    source: StorySource.LN,
    location: 'tempest_city',
  },
  {
    id: 'falmuth',
    title: 'Invasion de Farmus',
    chronology: 9,
    summary: 'Farmus attaque Tempest pendant l\'absence de Rimuru. Morts, colère, évolution.',
    source: StorySource.LN,
    location: 'tempest_invasion',
  },
  {
    id: 'demon_lord',
    title: 'Seigneur Démon',
    chronology: 10,
    summary: 'Harvest Festival, Diablo, nouvelle génération de Rimuru.',
    source: StorySource.LN,
    location: 'tempest_city',
  },
  {
    id: 'clayman',
    title: 'Clayman',
    chronology: 11,
    summary: 'Marionnettes, Eurazania, Milim, piège de Clayman.',
    source: StorySource.LN,
    location: 'eurazania',
  },
  {
    id: 'walpurgis',
    title: 'Walpurgis',
    chronology: 12,
    summary: 'Banquet des Demon Lords. Jugement de Clayman. Rimuru parmi eux.',
    source: StorySource.LN,
    location: 'walpurgis',
  },
]
