import { FighterId } from '../../types/game.ts'
import { StorySource, type StoryMissionDef } from '../types.ts'

/** LN vol. 1. Veldora nomme Rimuru ; Rimuru propose Tempest. Puis Predator. */
export const CAVE_MISSION: StoryMissionDef = {
  id: 'cave_veldora',
  title: 'Le dragon scellé',
  arc: 'sealed_cave',
  chronology: 2,
  location: 'Grotte Scellée',
  stageId: 'sealed_cave',
  summary: 'Faune de la grotte, Water Blade, Veldora. Échange de noms : Rimuru Tempest. Predator pour analyser le sceau.',
  source: StorySource.LN,
  playable: true,
  playableCharacter: FighterId.rimuru,
  objectives: [
    'Explorer la grotte',
    'Survivre à la faune',
    'Obtenir Water Blade',
    'Échanger les noms avec Veldora',
  ],
  rewards: { xp: 80, coins: 40 },
  unlocks: {
    skills: ['water-blade'],
    stages: ['sealed_cave', 'jura_forest'],
    archives: ['sealed-cave', 'water-blade', 'veldora-sealed'],
    tutorials: ['move', 'attack', 'skill1'],
  },
  beats: [
    {
      type: 'dialogue',
      speaker: 'Great Sage',
      speakerId: 'rimuru',
      text: 'Réponse. Densité magique élevée. Environnement : caverne. Présence scellée en profondeur.',
      emotion: 'serious',
    },
    { type: 'hint', text: 'Déplace-toi.' },
    { type: 'wait', input: 'move' },
    {
      type: 'dialogue',
      speaker: 'Great Sage',
      speakerId: 'rimuru',
      text: 'Réponse. Forme de vie hostile détectée.',
      emotion: 'serious',
    },
    { type: 'spawn', enemy: 'giant_bat', x: 980 },
    { type: 'wait', input: 'attack' },
    { type: 'clear' },
    { type: 'spawn', enemy: 'giant_bat', x: 1100 },
    { type: 'spawn', enemy: 'giant_bat', x: 1280 },
    { type: 'clear' },
    {
      type: 'dialogue',
      speaker: 'Great Sage',
      speakerId: 'rimuru',
      text: 'Réponse. Analyse terminée. Extra Skill [Water Blade] : reproductible. Enregistrement achevé.',
      emotion: 'normal',
    },
    { type: 'unlock', unlocks: { skills: ['water-blade'], tutorials: ['skill1'] } },
    { type: 'hint', text: 'Utilise Water Blade.' },
    { type: 'spawn', enemy: 'evil_centipede', x: 1200 },
    { type: 'wait', input: 'skill1' },
    { type: 'clear' },
    { type: 'presence', who: 'veldora' },
    { type: 'goto', x: 1380, hint: 'Le sceau est au fond. Avance.' },
    { type: 'narration', text: 'Rimuru s\'approche du sceau au fond de la grotte.' },
    {
      type: 'dialogue',
      speaker: 'Veldora',
      speakerId: 'veldora',
      text: 'Ah-ah-ah-ah ! Un visiteur ! Petit slime, tu n\'as pas peur ? Je suis Veldora, Dragon de la Tempête ! Immortel ! Parfait !',
      emotion: 'excited',
    },
    {
      type: 'dialogue',
      speaker: 'Rimuru',
      speakerId: 'rimuru',
      text: 'Tu parles beaucoup pour quelqu\'un dans une cage. Un héros t\'a mis là, non ?',
      emotion: 'normal',
    },
    {
      type: 'dialogue',
      speaker: 'Veldora',
      speakerId: 'veldora',
      text: 'Trois cents ans ! [Unlimited Imprisonment] ! Personne pour discuter, rien à lire, rien à faire ! Je m\'ennuie à mourir !',
      emotion: 'angry',
    },
    {
      type: 'dialogue',
      speaker: 'Veldora',
      speakerId: 'veldora',
      text: 'Échangeons nos noms. Comme un nom de famille humain. Ça gravera dans nos âmes que nous sommes égaux. Toi, tu n\'en as pas. Tu seras Rimuru. Named monster, enfin !',
      emotion: 'serious',
    },
    {
      type: 'dialogue',
      speaker: 'Rimuru',
      speakerId: 'rimuru',
      text: 'Rimuru... d\'accord. Et pour le nom qu\'on partage : Tempest. Dragon de la Tempête, ça colle.',
      emotion: 'normal',
    },
    {
      type: 'dialogue',
      speaker: 'Veldora',
      speakerId: 'veldora',
      text: 'Parfait ! Désormais : Veldora Tempest ! Et toi : Rimuru Tempest ! Proclame-le au monde !',
      emotion: 'happy',
    },
    {
      type: 'dialogue',
      speaker: 'Great Sage',
      speakerId: 'rimuru',
      text: 'Réponse. Nom gravé. Individu : Rimuru Tempest. Protection : Storm Crest. Named monster : confirmé.',
      emotion: 'serious',
    },
    {
      type: 'dialogue',
      speaker: 'Rimuru',
      speakerId: 'rimuru',
      text: 'Le sceau, je peux l\'analyser si je t\'avale avec [Predator]. Pas te digérer. Te garder. Jusqu\'à ce qu\'on casse cette prison.',
      emotion: 'serious',
    },
    {
      type: 'dialogue',
      speaker: 'Veldora',
      speakerId: 'veldora',
      text: 'Fais-le ! Enfin un ami ! Je te fais confiance, Rimuru !',
      emotion: 'happy',
    },
    { type: 'complete' },
  ],
}
