import { FighterId } from '../../types/game.ts'
import { StorySource, type StoryMissionDef } from '../types.ts'

/** LN vol. 5. Farmus. Rimuru est à Dwargon pendant le massacre. Le combat joué est la contre-attaque. */
export const FALMUTH_MISSION: StoryMissionDef = {
  id: 'falmuth_invasion',
  title: 'Farmus',
  arc: 'falmuth',
    chronology: 9,
  location: 'Royaume de Farmus — Tempest',
  stageId: 'tempest_invasion',
  summary: 'Rimuru absent (Dwargon). Farmus massacre Tempest. Shion meurt. Rimuru revient, puis anéantit l\'armée. 10 000 âmes.',
  source: StorySource.LN,
  playable: true,
  playableCharacter: FighterId.rimuru,
  objectives: ['Apprendre le massacre', 'Contre-attaquer l\'armée de Farmus', 'Choisir le Harvest Festival'],
  rewards: { xp: 150, coins: 90 },
  unlocks: {
    stages: ['tempest_invasion', 'dwargon'],
    archives: ['falmuth', 'shion-fall', 'edmaris', 'rimuru-rage'],
  },
  beats: [
    { type: 'title', text: 'DWARGON', sub: 'Rimuru n\'est pas à Tempest.', ms: 2000 },
    {
      type: 'dialogue',
      speaker: 'Gazel Dwargo',
      text: 'Le traité tient. Rentre chez toi, Rimuru. ...Tes ombres ne répondent plus.',
      emotion: 'serious',
    },
    {
      type: 'dialogue',
      speaker: 'Rimuru',
      speakerId: 'rimuru',
      text: 'Souei ? Benimaru ? ...Silence. Je rentre. Maintenant.',
      emotion: 'scared',
    },
    { type: 'title', text: 'TEMPEST', sub: 'La barrière sainte. Les morts. Shion.', ms: 2400 },
    { type: 'narration', text: 'Rimuru revient. La cité est en ruines. Shion ne respire plus.' },
    {
      type: 'dialogue',
      speaker: 'Benimaru',
      speakerId: 'benimaru',
      text: 'Tu étais à Dwargon. Ils ont levé un champ. On ne pouvait plus se battre comme avant. Shion... et plus de cent autres. Farmus a laissé un délai. Une « leçon ».',
      emotion: 'sad',
    },
    {
      type: 'dialogue',
      speaker: 'Rimuru',
      speakerId: 'rimuru',
      text: 'Shion. Je... je les ramène. Tous. S\'il le faut, je paie le prix qu\'on ne devrait pas payer.',
      emotion: 'sad',
    },
    {
      type: 'dialogue',
      speaker: 'Great Sage',
      speakerId: 'rimuru',
      text: 'Réponse. Resurrection possible si évolution en True Demon Lord. Condition estimée : environ dix mille âmes humaines. Armée de Farmus en approche : vingt mille.',
      emotion: 'serious',
    },
    {
      type: 'dialogue',
      speaker: 'Rimuru',
      speakerId: 'rimuru',
      text: 'Alors je les prends. Edmaris a voulu une guerre sainte. Il aura un Demon Lord.',
      emotion: 'angry',
    },
    { type: 'heal' },
    { type: 'spawn', enemy: 'falmuth_soldier', x: 1000 },
    { type: 'spawn', enemy: 'falmuth_soldier', x: 1180 },
    { type: 'spawn', enemy: 'falmuth_knight', x: 1380 },
    { type: 'hint', text: 'Contre-attaque.' },
    { type: 'clear' },
    { type: 'heal' },
    { type: 'spawn', enemy: 'falmuth_knight', x: 1100 },
    { type: 'spawn', enemy: 'falmuth_soldier', x: 1280 },
    { type: 'spawn', enemy: 'falmuth_knight', x: 1460 },
    { type: 'clear' },
    { type: 'title', text: 'DIX MILLE ÂMES', sub: 'Le Harvest Festival peut commencer.', ms: 2200 },
    { type: 'unlock', unlocks: { archives: ['falmuth', 'shion-fall', 'rimuru-rage'] } },
    { type: 'complete' },
  ],
}
