import { FighterId } from '../../types/game.ts'
import { StorySource, type StoryMissionDef } from '../types.ts'

/** LN vol. 1. Les gobelins viennent parce que l'aura de Veldora a disparu. */
export const GOBLIN_MISSION: StoryMissionDef = {
  id: 'goblin_wolves',
  title: 'Les gobelins de Jura',
  arc: 'goblins',
  chronology: 3,
  location: 'Grande Forêt de Jura',
  stageId: 'jura_forest',
  summary: 'Les gobelins cherchaient la protection du dragon. Rimuru nomme Rigurd, puis Ranga après la meute.',
  source: StorySource.LN,
  playable: true,
  playableCharacter: FighterId.rimuru,
  objectives: ['Nommer Rigurd, Rigur, Gobta', 'Repousser la meute', 'Nommer Ranga'],
  rewards: { xp: 70, coins: 35 },
  unlocks: {
    characters: ['ranga'],
    stages: ['jura_forest'],
    archives: ['goblin-village', 'rigurd', 'ranga', 'direwolves'],
    tutorials: ['guard'],
  },
  beats: [
    {
      type: 'dialogue',
      speaker: 'Chef gobelin',
      text: 'Nous n\'avons plus de protecteur. L\'aura du Dragon de la Tempête... elle s\'est tue. Les loups n\'ont plus peur. Seigneur slime, protégez-nous !',
      emotion: 'scared',
    },
    {
      type: 'dialogue',
      speaker: 'Rimuru',
      speakerId: 'rimuru',
      text: 'Veldora est avec moi. Je ne le « remplace » pas. Mais je peux vous aider. Toi, le chef : Rigurd.',
      emotion: 'normal',
    },
    {
      type: 'dialogue',
      speaker: 'Rigurd',
      text: 'Rigurd... Un nom... Seigneur Rimuru ! Le village est à vous !',
      emotion: 'happy',
    },
    {
      type: 'dialogue',
      speaker: 'Rimuru',
      speakerId: 'rimuru',
      text: 'Toi, le scout : Rigur. Même nom que ton frère disparu. Porte-le mieux.',
      emotion: 'normal',
    },
    {
      type: 'dialogue',
      speaker: 'Rigur',
      text: 'Rigur... Je le porterai. Seigneur Rimuru !',
      emotion: 'happy',
    },
    {
      type: 'dialogue',
      speaker: 'Rimuru',
      speakerId: 'rimuru',
      text: 'Et toi, le petit nerveux : Gobta.',
      emotion: 'normal',
    },
    {
      type: 'dialogue',
      speaker: 'Gobta',
      text: 'Gobta ! Oui, chef ! Je... je tiendrai !',
      emotion: 'excited',
    },
    { type: 'unlock', unlocks: { archives: ['rigurd', 'rigur', 'gobta', 'goblin-village'] } },
    {
      type: 'dialogue',
      speaker: 'Great Sage',
      speakerId: 'rimuru',
      text: 'Réponse. Meute : direwolves. Ils chassaient sous la terreur de Veldora. Cette terreur n\'est plus.',
      emotion: 'serious',
    },
    { type: 'spawn', enemy: 'direwolf', x: 1180 },
    { type: 'hint', text: 'Garde-toi.' },
    { type: 'wait', input: 'guard' },
    { type: 'spawn', enemy: 'direwolf', x: 1380 },
    { type: 'clear' },
    {
      type: 'dialogue',
      speaker: 'Chef de la meute',
      text: 'Nous avons perdu. La loi des monstres est claire. Un nom, et la meute t\'appartient.',
      emotion: 'serious',
    },
    {
      type: 'dialogue',
      speaker: 'Rimuru',
      speakerId: 'rimuru',
      text: 'Ranga. Tempête et croc. Plus de chasse contre ce village. Vous vivez avec eux.',
      emotion: 'normal',
    },
    {
      type: 'dialogue',
      speaker: 'Ranga',
      text: 'Ranga... Maître Rimuru. La meute entend. Nous évoluerons pour toi.',
      emotion: 'happy',
    },
    { type: 'unlock', unlocks: { characters: ['ranga'], archives: ['ranga'], tutorials: ['guard'] } },
    { type: 'complete' },
  ],
}
