import { FighterId } from '../../types/game.ts'
import { StorySource, type StoryMissionDef } from '../types.ts'

/** LN vol. 1. Six survivants. D'abord le combat, ensuite les noms, évolution kijin. */
export const OGRES_MISSION: StoryMissionDef = {
  id: 'ogres_survivors',
  title: 'Les six ogres',
  arc: 'ogres',
  chronology: 4,
  location: 'Grande Forêt de Jura',
  stageId: 'jura_forest',
  summary: 'Village ogre détruit par les orcs. Combat d\'abord. Noms : Benimaru, Shion, Shuna, Souei, Hakurou, Kurobe.',
  source: StorySource.LN,
  playable: true,
  playableCharacter: FighterId.rimuru,
  objectives: [
    'Soutenir le choc sans massacrer les ogres',
    'Repousser les orcs qui les chassent',
    'Nommer les six survivants',
  ],
  rewards: { xp: 90, coins: 50 },
  unlocks: {
    characters: ['benimaru', 'shion', 'shuna', 'souei', 'hakurou'],
    stages: ['jura_forest'],
    archives: ['benimaru', 'shion', 'shuna', 'souei', 'hakurou', 'kurobe', 'ogre-survivors'],
    tutorials: ['guard', 'combo'],
  },
  beats: [
    { type: 'title', text: 'LES SURVIVANTS', sub: 'L\'armée orc a brûlé le village ogre.', ms: 2000 },
    {
      type: 'dialogue',
      speaker: 'Rigurd',
      text: 'Seigneur Rimuru ! Des ogres... Ils fuient. Leur village n\'existe plus.',
      emotion: 'scared',
    },
    { type: 'presence', who: 'benimaru' },
    { type: 'narration', text: 'Benimaru avance, la lame encore chaude de la fuite.' },
    {
      type: 'dialogue',
      speaker: 'Benimaru',
      speakerId: 'benimaru',
      text: 'Tout a brûlé. Notre peuple aussi. Si tu es avec les orcs, slime, je te tuerai ici.',
      emotion: 'angry',
    },
    {
      type: 'dialogue',
      speaker: 'Shion',
      speakerId: 'shion',
      text: 'On n\'a plus rien à perdre. Je coupe ce qui bouge.',
      emotion: 'angry',
    },
    {
      type: 'dialogue',
      speaker: 'Rimuru',
      speakerId: 'rimuru',
      text: 'Ce n\'est pas moi. Si quelqu\'un doit payer le village, ce sont les orcs. On peut en parler après, si vous voulez encore vivre.',
      emotion: 'serious',
    },
    { type: 'hint', text: 'Frappe.' },
    { type: 'wait', input: 'attack' },
    {
      type: 'dialogue',
      speaker: 'Hakurou',
      speakerId: 'hakurou',
      text: 'Assez. Toi, slime, tu n\'as pas l\'odeur de l\'armée orc. Derrière nous, les poursuivants n\'ont pas fini.',
      emotion: 'serious',
    },
    { type: 'spawn', enemy: 'orc_soldier', x: 1080 },
    { type: 'spawn', enemy: 'orc_soldier', x: 1280 },
    { type: 'spawn', enemy: 'orc_raider', x: 1480 },
    { type: 'hint', text: 'Garde-toi.' },
    { type: 'wait', input: 'guard' },
    { type: 'clear' },
    {
      type: 'dialogue',
      speaker: 'Shuna',
      speakerId: 'shuna',
      text: 'Vous avez combattu pour nous. Un nom, comme pour les gobelins, peut-être nous sauver. Je vous en prie.',
      emotion: 'sad',
    },
    {
      type: 'dialogue',
      speaker: 'Rimuru',
      speakerId: 'rimuru',
      text: 'Benimaru. Shion. Shuna. Souei. Hakurou. Et le forgeron : Kurobe. Vous n\'êtes plus six égarés.',
      emotion: 'serious',
    },
    {
      type: 'dialogue',
      speaker: 'Benimaru',
      speakerId: 'benimaru',
      text: 'Benimaru... Je le porterai. Rimuru, nos lames sont à toi.',
      emotion: 'serious',
    },
    {
      type: 'dialogue',
      speaker: 'Souei',
      speakerId: 'souei',
      text: 'Souei. L\'ombre du village. Rien n\'approchera sans que je le sache.',
      emotion: 'serious',
    },
    {
      type: 'dialogue',
      speaker: 'Great Sage',
      speakerId: 'rimuru',
      text: 'Réponse. Noms reçus. Évolution : ogre → kijin. Six individus. Kurobe : artisan, pas première ligne.',
      emotion: 'serious',
    },
    { type: 'transform', who: FighterId.benimaru, appearanceId: 'benimaru-kijin' },
    {
      type: 'unlock',
      unlocks: {
        characters: ['benimaru', 'shion', 'shuna', 'souei', 'hakurou'],
        archives: ['benimaru', 'shion', 'shuna', 'souei', 'hakurou', 'kurobe'],
        tutorials: ['guard'],
      },
    },
    { type: 'complete' },
  ],
}
