import { FighterId } from '../../types/game.ts'
import { StorySource, type StoryMissionDef } from '../types.ts'

/** LN vol. 1. Gelmud, famine, Gabiru, Orc Disaster, puis le nom Geld. */
export const ORC_MISSION: StoryMissionDef = {
  id: 'orc_war',
  title: 'La guerre des Orcs',
  arc: 'orcs',
  chronology: 5,
  location: 'Grande Forêt de Jura',
  stageId: 'jura_forest',
  summary: 'Famine magique, nom de Gelmud, Gabiru, Seigneur Orc. Rimuru nomme Geld. Les orcs construisent ensuite.',
  source: StorySource.LN,
  playable: true,
  playableCharacter: FighterId.rimuru,
  objectives: ['Repousser les vagues orcs', 'Vaincre le Seigneur Orc', 'Nommer Geld'],
  rewards: { xp: 120, coins: 70 },
  unlocks: {
    characters: ['geld', 'gabiru'],
    stages: ['jura_forest'],
    archives: ['orc-war', 'orc-disaster', 'geld', 'gabiru', 'gelmud'],
    tutorials: ['dash'],
  },
  beats: [
    { type: 'title', text: 'LA GUERRE DES ORCS', sub: 'Jura. Une nation affamée marche.', ms: 2000 },
    {
      type: 'dialogue',
      speaker: 'Benimaru',
      speakerId: 'benimaru',
      text: 'Ce n\'est plus une bande. C\'est une armée. Ils mangent forêts, villages, leurs morts. La faim les pousse.',
      emotion: 'serious',
    },
    {
      type: 'dialogue',
      speaker: 'Gabiru',
      text: 'Moi, Gabiru, héros des lizardmen, je les écrase ! Mon père Abiru n\'a qu\'à regarder !',
      emotion: 'excited',
    },
    {
      type: 'dialogue',
      speaker: 'Hakurou',
      speakerId: 'hakurou',
      text: 'Tu vas te faire dévorer. Chez eux, la raison a déjà été mangée.',
      emotion: 'serious',
    },
    { type: 'spawn', enemy: 'orc_soldier', x: 1040 },
    { type: 'spawn', enemy: 'orc_soldier', x: 1220 },
    { type: 'spawn', enemy: 'orc_raider', x: 1400 },
    { type: 'hint', text: 'Esquive.' },
    { type: 'wait', input: 'dash' },
    { type: 'clear' },
    {
      type: 'dialogue',
      speaker: 'Gabiru',
      text: 'Seigneur slime... mes hommes... je ne peux plus. Aidez-nous.',
      emotion: 'scared',
    },
    {
      type: 'dialogue',
      speaker: 'Great Sage',
      speakerId: 'rimuru',
      text: 'Réponse. Individu dominant : Orc Disaster. Nom antérieur attribué par Gelmud. La famine a tout dévoré, y compris lui.',
      emotion: 'serious',
    },
    { type: 'heal' },
    { type: 'spawn', enemy: 'orc_disaster', x: 1480 },
    { type: 'hint', text: 'Utilise Water Blade.' },
    { type: 'clear' },
    {
      type: 'dialogue',
      speaker: 'Rimuru',
      speakerId: 'rimuru',
      text: 'Tu as porté toute cette faim. Un vrai nom, cette fois : Geld. Tes orcs construiront. Ils ne dévoreront plus Jura.',
      emotion: 'serious',
    },
    {
      type: 'dialogue',
      speaker: 'Geld',
      text: 'Geld... Maître. Nous paierons en travail. Plus jamais cette faim. Plus jamais nos morts pour un mage.',
      emotion: 'sad',
    },
    { type: 'unlock', unlocks: { characters: ['geld', 'gabiru'], archives: ['geld', 'gabiru', 'orc-disaster'], tutorials: ['dash'] } },
    { type: 'complete' },
  ],
}
