/** Generated by scripts/prepare-skill-slots.mjs. Do not edit by hand. */
export interface SkillSlotRecord {
  fighterId: string
  attackId?: string
  animId: string
  skillName?: string
  slot?: number
  folder: string
  hasAnimJson: boolean
  kind: 'skill' | 'normal'
}

export const SKILL_SLOT_FOLDERS: SkillSlotRecord[] = [
  {
    "fighterId": "rimuru",
    "attackId": "water-blade",
    "animId": "rimuru_water_blade",
    "skillName": "Water Blade",
    "slot": 0,
    "folder": "public/sprites/rimuru/rimuru_water_blade",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "rimuru",
    "attackId": "black-lightning",
    "animId": "rimuru_black_lightning",
    "skillName": "Black Lightning",
    "slot": 1,
    "folder": "public/sprites/rimuru/rimuru_black_lightning",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "rimuru",
    "attackId": "predator",
    "animId": "rimuru_predator",
    "skillName": "Predator",
    "slot": 2,
    "folder": "public/sprites/rimuru/rimuru_predator",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "rimuru",
    "attackId": "megiddo",
    "animId": "rimuru_megiddo",
    "skillName": "Megiddo",
    "slot": 3,
    "folder": "public/sprites/rimuru/rimuru_megiddo",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "rimuru",
    "attackId": "rimuru-ult",
    "animId": "rimuru_beelzebuth",
    "skillName": "Beelzebuth",
    "slot": 4,
    "folder": "public/sprites/rimuru/rimuru_beelzebuth",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "milim",
    "attackId": "dragon-fist",
    "animId": "milim_dragon_fist",
    "skillName": "Dragon Fist",
    "slot": 0,
    "folder": "public/sprites/milim/milim_dragon_fist",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "milim",
    "attackId": "magic-missile",
    "animId": "milim_magic_missile",
    "skillName": "Magic Missile",
    "slot": 1,
    "folder": "public/sprites/milim/milim_magic_missile",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "milim",
    "attackId": "milim-kick",
    "animId": "milim_milim_kick",
    "skillName": "Milim Kick",
    "slot": 2,
    "folder": "public/sprites/milim/milim_milim_kick",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "milim",
    "attackId": "dragon-nova",
    "animId": "milim_dragon_nova",
    "skillName": "Dragon Nova",
    "slot": 3,
    "folder": "public/sprites/milim/milim_dragon_nova",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "milim",
    "attackId": "milim-ult",
    "animId": "milim_drago_buster",
    "skillName": "Drago Buster",
    "slot": 4,
    "folder": "public/sprites/milim/milim_drago_buster",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "diablo",
    "attackId": "end-of-world",
    "animId": "diablo_end_of_world",
    "skillName": "End of World",
    "slot": 0,
    "folder": "public/sprites/diablo/diablo_end_of_world",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "diablo",
    "attackId": "tempter",
    "animId": "diablo_tempter_counter",
    "skillName": "Tempter Counter",
    "slot": 1,
    "folder": "public/sprites/diablo/diablo_tempter_counter",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "diablo",
    "attackId": "dark-nova",
    "animId": "diablo_dark_nova",
    "skillName": "Dark Nova",
    "slot": 2,
    "folder": "public/sprites/diablo/diablo_dark_nova",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "diablo",
    "attackId": "demon-lord",
    "animId": "diablo_demon_form",
    "skillName": "Demon Form",
    "slot": 3,
    "folder": "public/sprites/diablo/diablo_demon_form",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "diablo",
    "attackId": "diablo-ult",
    "animId": "diablo_azazel",
    "skillName": "Azazel",
    "slot": 4,
    "folder": "public/sprites/diablo/diablo_azazel",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "benimaru",
    "attackId": "flame-slash",
    "animId": "benimaru_flame_slash",
    "skillName": "Flame Slash",
    "slot": 0,
    "folder": "public/sprites/benimaru/benimaru_flame_slash",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "benimaru",
    "attackId": "hellflare",
    "animId": "benimaru_hellflare",
    "skillName": "Hellflare",
    "slot": 1,
    "folder": "public/sprites/benimaru/benimaru_hellflare",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "benimaru",
    "attackId": "ogre-rush",
    "animId": "benimaru_ogre_rush",
    "skillName": "Ogre Rush",
    "slot": 2,
    "folder": "public/sprites/benimaru/benimaru_ogre_rush",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "benimaru",
    "attackId": "black-flame",
    "animId": "benimaru_black_flame",
    "skillName": "Black Flame",
    "slot": 3,
    "folder": "public/sprites/benimaru/benimaru_black_flame",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "benimaru",
    "attackId": "benimaru-ult",
    "animId": "benimaru_prominence",
    "skillName": "Prominence",
    "slot": 4,
    "folder": "public/sprites/benimaru/benimaru_prominence",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "shion",
    "attackId": "cleaver",
    "animId": "shion_chef_cleaver",
    "skillName": "Chef Cleaver",
    "slot": 0,
    "folder": "public/sprites/shion/shion_chef_cleaver",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "shion",
    "attackId": "cook",
    "animId": "shion_cook_throw",
    "skillName": "Cook Throw",
    "slot": 1,
    "folder": "public/sprites/shion/shion_cook_throw",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "shion",
    "attackId": "berserk",
    "animId": "shion_berserk",
    "skillName": "Berserk",
    "slot": 2,
    "folder": "public/sprites/shion/shion_berserk",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "shion",
    "attackId": "ground-break",
    "animId": "shion_ground_break",
    "skillName": "Ground Break",
    "slot": 3,
    "folder": "public/sprites/shion/shion_ground_break",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "shion",
    "attackId": "shion-ult",
    "animId": "shion_tempest_fury",
    "skillName": "Tempest Fury",
    "slot": 4,
    "folder": "public/sprites/shion/shion_tempest_fury",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "veldora",
    "attackId": "storm",
    "animId": "veldora_storm_breath",
    "skillName": "Storm Breath",
    "slot": 0,
    "folder": "public/sprites/veldora/veldora_storm_breath",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "veldora",
    "attackId": "dragon-tail",
    "animId": "veldora_dragon_tail",
    "skillName": "Dragon Tail",
    "slot": 1,
    "folder": "public/sprites/veldora/veldora_dragon_tail",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "veldora",
    "attackId": "thunder",
    "animId": "veldora_death_heralding_wind",
    "skillName": "Death-Heralding Wind",
    "slot": 2,
    "folder": "public/sprites/veldora/veldora_death_heralding_wind",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "veldora",
    "attackId": "roar",
    "animId": "veldora_storm_roar",
    "skillName": "Storm Roar",
    "slot": 3,
    "folder": "public/sprites/veldora/veldora_storm_roar",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "veldora",
    "attackId": "veldora-ult",
    "animId": "veldora_storm_dragon",
    "skillName": "Storm Dragon",
    "slot": 4,
    "folder": "public/sprites/veldora/veldora_storm_dragon",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "hinata",
    "attackId": "holy-cut",
    "animId": "hinata_holy_cut",
    "skillName": "Holy Cut",
    "slot": 0,
    "folder": "public/sprites/hinata/hinata_holy_cut",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "hinata",
    "attackId": "melt-slash",
    "animId": "hinata_melt_slash",
    "skillName": "Melt Slash",
    "slot": 1,
    "folder": "public/sprites/hinata/hinata_melt_slash",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "hinata",
    "attackId": "disintegration",
    "animId": "hinata_disintegration",
    "skillName": "Disintegration",
    "slot": 2,
    "folder": "public/sprites/hinata/hinata_disintegration",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "hinata",
    "attackId": "faith",
    "animId": "hinata_faith_guard",
    "skillName": "Faith Guard",
    "slot": 3,
    "folder": "public/sprites/hinata/hinata_faith_guard",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "hinata",
    "attackId": "hinata-ult",
    "animId": "hinata_chrono_saltation",
    "skillName": "Chrono-Saltation",
    "slot": 4,
    "folder": "public/sprites/hinata/hinata_chrono_saltation",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "guy",
    "attackId": "pride-cut",
    "animId": "guy_pride_cut",
    "skillName": "Pride Cut",
    "slot": 0,
    "folder": "public/sprites/guy/guy_pride_cut",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "guy",
    "attackId": "crimson",
    "animId": "guy_crimson_magic",
    "skillName": "Crimson Magic",
    "slot": 1,
    "folder": "public/sprites/guy/guy_crimson_magic",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "guy",
    "attackId": "dominate",
    "animId": "guy_dominate",
    "skillName": "Dominate",
    "slot": 2,
    "folder": "public/sprites/guy/guy_dominate",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "guy",
    "attackId": "lord",
    "animId": "guy_true_dragon_lord",
    "skillName": "True Dragon Lord",
    "slot": 3,
    "folder": "public/sprites/guy/guy_true_dragon_lord",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "guy",
    "attackId": "guy-ult",
    "animId": "guy_world_ruin",
    "skillName": "World Ruin",
    "slot": 4,
    "folder": "public/sprites/guy/guy_world_ruin",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "shuna",
    "attackId": "holy-flame",
    "animId": "shuna_holy_flame",
    "skillName": "Holy Flame",
    "slot": 0,
    "folder": "public/sprites/shuna/shuna_holy_flame",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "shuna",
    "attackId": "barrier",
    "animId": "shuna_barrier",
    "skillName": "Barrier",
    "slot": 1,
    "folder": "public/sprites/shuna/shuna_barrier",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "shuna",
    "attackId": "bless",
    "animId": "shuna_blessing",
    "skillName": "Blessing",
    "slot": 2,
    "folder": "public/sprites/shuna/shuna_blessing",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "shuna",
    "attackId": "purify",
    "animId": "shuna_purify",
    "skillName": "Purify",
    "slot": 3,
    "folder": "public/sprites/shuna/shuna_purify",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "shuna",
    "attackId": "shuna-ult",
    "animId": "shuna_temple_light",
    "skillName": "Temple Light",
    "slot": 4,
    "folder": "public/sprites/shuna/shuna_temple_light",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "souei",
    "attackId": "shadow-stab",
    "animId": "souei_shadow_blade",
    "skillName": "Shadow Blade",
    "slot": 0,
    "folder": "public/sprites/souei/souei_shadow_blade",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "souei",
    "attackId": "clone",
    "animId": "souei_clone_dash",
    "skillName": "Clone Dash",
    "slot": 1,
    "folder": "public/sprites/souei/souei_clone_dash",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "souei",
    "attackId": "kunai",
    "animId": "souei_shadow_kunai",
    "skillName": "Shadow Kunai",
    "slot": 2,
    "folder": "public/sprites/souei/souei_shadow_kunai",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "souei",
    "attackId": "assassinate",
    "animId": "souei_assassinate",
    "skillName": "Assassinate",
    "slot": 3,
    "folder": "public/sprites/souei/souei_assassinate",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "souei",
    "attackId": "souei-ult",
    "animId": "souei_death_shadow",
    "skillName": "Death Shadow",
    "slot": 4,
    "folder": "public/sprites/souei/souei_death_shadow",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "hakurou",
    "attackId": "iai",
    "animId": "hakurou_iai",
    "skillName": "Iai",
    "slot": 0,
    "folder": "public/sprites/hakurou/hakurou_iai",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "hakurou",
    "attackId": "form-two",
    "animId": "hakurou_second_form",
    "skillName": "Second Form",
    "slot": 1,
    "folder": "public/sprites/hakurou/hakurou_second_form",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "hakurou",
    "attackId": "parry",
    "animId": "hakurou_sword_parry",
    "skillName": "Sword Parry",
    "slot": 2,
    "folder": "public/sprites/hakurou/hakurou_sword_parry",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "hakurou",
    "attackId": "secret",
    "animId": "hakurou_secret_art",
    "skillName": "Secret Art",
    "slot": 3,
    "folder": "public/sprites/hakurou/hakurou_secret_art",
    "hasAnimJson": true,
    "kind": "skill"
  },
  {
    "fighterId": "hakurou",
    "attackId": "hakurou-ult",
    "animId": "hakurou_moon_fang",
    "skillName": "Moon Fang",
    "slot": 4,
    "folder": "public/sprites/hakurou/hakurou_moon_fang",
    "hasAnimJson": true,
    "kind": "skill"
  }
]

export const NORMAL_SLOT_FOLDERS: SkillSlotRecord[] = [
  {
    "fighterId": "rimuru",
    "animId": "rimuru_light_1",
    "folder": "public/sprites/rimuru/rimuru_light_1",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "rimuru",
    "animId": "rimuru_light_2",
    "folder": "public/sprites/rimuru/rimuru_light_2",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "rimuru",
    "animId": "rimuru_light_3",
    "folder": "public/sprites/rimuru/rimuru_light_3",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "rimuru",
    "animId": "rimuru_medium",
    "folder": "public/sprites/rimuru/rimuru_medium",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "rimuru",
    "animId": "rimuru_heavy",
    "folder": "public/sprites/rimuru/rimuru_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "rimuru",
    "animId": "rimuru_air_light",
    "folder": "public/sprites/rimuru/rimuru_air_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "rimuru",
    "animId": "rimuru_air_heavy",
    "folder": "public/sprites/rimuru/rimuru_air_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "rimuru",
    "animId": "rimuru_down_light",
    "folder": "public/sprites/rimuru/rimuru_down_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "milim",
    "animId": "milim_light_1",
    "folder": "public/sprites/milim/milim_light_1",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "milim",
    "animId": "milim_light_2",
    "folder": "public/sprites/milim/milim_light_2",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "milim",
    "animId": "milim_light_3",
    "folder": "public/sprites/milim/milim_light_3",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "milim",
    "animId": "milim_medium",
    "folder": "public/sprites/milim/milim_medium",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "milim",
    "animId": "milim_heavy",
    "folder": "public/sprites/milim/milim_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "milim",
    "animId": "milim_air_light",
    "folder": "public/sprites/milim/milim_air_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "milim",
    "animId": "milim_air_heavy",
    "folder": "public/sprites/milim/milim_air_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "milim",
    "animId": "milim_down_light",
    "folder": "public/sprites/milim/milim_down_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "diablo",
    "animId": "diablo_light_1",
    "folder": "public/sprites/diablo/diablo_light_1",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "diablo",
    "animId": "diablo_light_2",
    "folder": "public/sprites/diablo/diablo_light_2",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "diablo",
    "animId": "diablo_light_3",
    "folder": "public/sprites/diablo/diablo_light_3",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "diablo",
    "animId": "diablo_medium",
    "folder": "public/sprites/diablo/diablo_medium",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "diablo",
    "animId": "diablo_heavy",
    "folder": "public/sprites/diablo/diablo_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "diablo",
    "animId": "diablo_air_light",
    "folder": "public/sprites/diablo/diablo_air_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "diablo",
    "animId": "diablo_air_heavy",
    "folder": "public/sprites/diablo/diablo_air_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "diablo",
    "animId": "diablo_down_light",
    "folder": "public/sprites/diablo/diablo_down_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "benimaru",
    "animId": "benimaru_light_1",
    "folder": "public/sprites/benimaru/benimaru_light_1",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "benimaru",
    "animId": "benimaru_light_2",
    "folder": "public/sprites/benimaru/benimaru_light_2",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "benimaru",
    "animId": "benimaru_light_3",
    "folder": "public/sprites/benimaru/benimaru_light_3",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "benimaru",
    "animId": "benimaru_medium",
    "folder": "public/sprites/benimaru/benimaru_medium",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "benimaru",
    "animId": "benimaru_heavy",
    "folder": "public/sprites/benimaru/benimaru_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "benimaru",
    "animId": "benimaru_air_light",
    "folder": "public/sprites/benimaru/benimaru_air_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "benimaru",
    "animId": "benimaru_air_heavy",
    "folder": "public/sprites/benimaru/benimaru_air_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "benimaru",
    "animId": "benimaru_down_light",
    "folder": "public/sprites/benimaru/benimaru_down_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shion",
    "animId": "shion_light_1",
    "folder": "public/sprites/shion/shion_light_1",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shion",
    "animId": "shion_light_2",
    "folder": "public/sprites/shion/shion_light_2",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shion",
    "animId": "shion_light_3",
    "folder": "public/sprites/shion/shion_light_3",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shion",
    "animId": "shion_medium",
    "folder": "public/sprites/shion/shion_medium",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shion",
    "animId": "shion_heavy",
    "folder": "public/sprites/shion/shion_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shion",
    "animId": "shion_air_light",
    "folder": "public/sprites/shion/shion_air_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shion",
    "animId": "shion_air_heavy",
    "folder": "public/sprites/shion/shion_air_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shion",
    "animId": "shion_down_light",
    "folder": "public/sprites/shion/shion_down_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "veldora",
    "animId": "veldora_light_1",
    "folder": "public/sprites/veldora/veldora_light_1",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "veldora",
    "animId": "veldora_light_2",
    "folder": "public/sprites/veldora/veldora_light_2",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "veldora",
    "animId": "veldora_light_3",
    "folder": "public/sprites/veldora/veldora_light_3",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "veldora",
    "animId": "veldora_medium",
    "folder": "public/sprites/veldora/veldora_medium",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "veldora",
    "animId": "veldora_heavy",
    "folder": "public/sprites/veldora/veldora_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "veldora",
    "animId": "veldora_air_light",
    "folder": "public/sprites/veldora/veldora_air_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "veldora",
    "animId": "veldora_air_heavy",
    "folder": "public/sprites/veldora/veldora_air_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "veldora",
    "animId": "veldora_down_light",
    "folder": "public/sprites/veldora/veldora_down_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hinata",
    "animId": "hinata_light_1",
    "folder": "public/sprites/hinata/hinata_light_1",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hinata",
    "animId": "hinata_light_2",
    "folder": "public/sprites/hinata/hinata_light_2",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hinata",
    "animId": "hinata_light_3",
    "folder": "public/sprites/hinata/hinata_light_3",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hinata",
    "animId": "hinata_medium",
    "folder": "public/sprites/hinata/hinata_medium",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hinata",
    "animId": "hinata_heavy",
    "folder": "public/sprites/hinata/hinata_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hinata",
    "animId": "hinata_air_light",
    "folder": "public/sprites/hinata/hinata_air_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hinata",
    "animId": "hinata_air_heavy",
    "folder": "public/sprites/hinata/hinata_air_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hinata",
    "animId": "hinata_down_light",
    "folder": "public/sprites/hinata/hinata_down_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "guy",
    "animId": "guy_light_1",
    "folder": "public/sprites/guy/guy_light_1",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "guy",
    "animId": "guy_light_2",
    "folder": "public/sprites/guy/guy_light_2",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "guy",
    "animId": "guy_light_3",
    "folder": "public/sprites/guy/guy_light_3",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "guy",
    "animId": "guy_medium",
    "folder": "public/sprites/guy/guy_medium",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "guy",
    "animId": "guy_heavy",
    "folder": "public/sprites/guy/guy_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "guy",
    "animId": "guy_air_light",
    "folder": "public/sprites/guy/guy_air_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "guy",
    "animId": "guy_air_heavy",
    "folder": "public/sprites/guy/guy_air_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "guy",
    "animId": "guy_down_light",
    "folder": "public/sprites/guy/guy_down_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shuna",
    "animId": "shuna_light_1",
    "folder": "public/sprites/shuna/shuna_light_1",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shuna",
    "animId": "shuna_light_2",
    "folder": "public/sprites/shuna/shuna_light_2",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shuna",
    "animId": "shuna_light_3",
    "folder": "public/sprites/shuna/shuna_light_3",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shuna",
    "animId": "shuna_medium",
    "folder": "public/sprites/shuna/shuna_medium",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shuna",
    "animId": "shuna_heavy",
    "folder": "public/sprites/shuna/shuna_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shuna",
    "animId": "shuna_air_light",
    "folder": "public/sprites/shuna/shuna_air_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shuna",
    "animId": "shuna_air_heavy",
    "folder": "public/sprites/shuna/shuna_air_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "shuna",
    "animId": "shuna_down_light",
    "folder": "public/sprites/shuna/shuna_down_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "souei",
    "animId": "souei_light_1",
    "folder": "public/sprites/souei/souei_light_1",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "souei",
    "animId": "souei_light_2",
    "folder": "public/sprites/souei/souei_light_2",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "souei",
    "animId": "souei_light_3",
    "folder": "public/sprites/souei/souei_light_3",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "souei",
    "animId": "souei_medium",
    "folder": "public/sprites/souei/souei_medium",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "souei",
    "animId": "souei_heavy",
    "folder": "public/sprites/souei/souei_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "souei",
    "animId": "souei_air_light",
    "folder": "public/sprites/souei/souei_air_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "souei",
    "animId": "souei_air_heavy",
    "folder": "public/sprites/souei/souei_air_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "souei",
    "animId": "souei_down_light",
    "folder": "public/sprites/souei/souei_down_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hakurou",
    "animId": "hakurou_light_1",
    "folder": "public/sprites/hakurou/hakurou_light_1",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hakurou",
    "animId": "hakurou_light_2",
    "folder": "public/sprites/hakurou/hakurou_light_2",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hakurou",
    "animId": "hakurou_light_3",
    "folder": "public/sprites/hakurou/hakurou_light_3",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hakurou",
    "animId": "hakurou_medium",
    "folder": "public/sprites/hakurou/hakurou_medium",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hakurou",
    "animId": "hakurou_heavy",
    "folder": "public/sprites/hakurou/hakurou_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hakurou",
    "animId": "hakurou_air_light",
    "folder": "public/sprites/hakurou/hakurou_air_light",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hakurou",
    "animId": "hakurou_air_heavy",
    "folder": "public/sprites/hakurou/hakurou_air_heavy",
    "hasAnimJson": true,
    "kind": "normal"
  },
  {
    "fighterId": "hakurou",
    "animId": "hakurou_down_light",
    "folder": "public/sprites/hakurou/hakurou_down_light",
    "hasAnimJson": true,
    "kind": "normal"
  }
]
