import fs from 'node:fs'
import path from 'node:path'

const root = path.resolve('public/sprites')
const outFile = path.resolve('src/sprites/spriteClipIndex.ts')
const sheetOut = path.resolve('src/sprites/spriteSheetIndex.ts')

const SEQ = /^(?:frame[_-])?(\d+)\.(?:png|webp)$/i
const SHEETS = new Set(['sheet.png', 'spritesheet.png', 'atlas.png'])

function listSequence(dir) {
  if (!fs.existsSync(dir)) {
    return []
  }
  const frames = []
  for (const name of fs.readdirSync(dir)) {
    if (SHEETS.has(name.toLowerCase())) {
      continue
    }
    const match = name.match(SEQ)
    if (match) {
      frames.push({ index: Number(match[1]), name })
    }
  }
  frames.sort((a, b) => a.index - b.index || a.name.localeCompare(b.name, 'en'))
  return frames.map((item) => item.name)
}

function addClip(clips, key, files) {
  if (files.length > 0 && !clips[key]) {
    clips[key] = files
  }
}

function readMeta(dir) {
  const file = path.join(dir, 'anim.json')
  if (!fs.existsSync(file)) {
    return null
  }
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'))
  } catch {
    return null
  }
}

const index = {}
const sheets = {}
for (const fighter of fs.readdirSync(root, { withFileTypes: true })) {
  if (!fighter.isDirectory()) {
    continue
  }
  const clips = {}
  const fighterSheets = {}
  const fighterDir = path.join(root, fighter.name)
  for (const child of fs.readdirSync(fighterDir, { withFileTypes: true })) {
    if (!child.isDirectory() || child.name.startsWith('_')) {
      continue
    }
    const childDir = path.join(fighterDir, child.name)
    const direct = listSequence(childDir)
    addClip(clips, child.name, direct.map((name) => `${child.name}/${name}`))
    const meta = readMeta(childDir)
    const sheetFile = ['sheet.png', 'spritesheet.png', meta?.sheet].filter(Boolean).find((name) => fs.existsSync(path.join(childDir, name)))
    if (sheetFile && (meta?.type === 'spritesheet' || !direct.length)) {
      fighterSheets[child.name] = {
        file: `${child.name}/${sheetFile}`,
        frameWidth: meta?.frameWidth ?? 0,
        frameHeight: meta?.frameHeight ?? 0,
        frames: meta?.frames ?? meta?.frameCount ?? 0,
        columns: meta?.columns ?? 0,
        rows: meta?.rows ?? 0,
        fps: meta?.fps ?? 12,
        loop: Boolean(meta?.loop),
        anchorX: meta?.anchorX,
        anchorY: meta?.anchorY,
      }
    }
    for (const nested of fs.readdirSync(childDir, { withFileTypes: true })) {
      if (!nested.isDirectory()) {
        continue
      }
      const nestedDir = path.join(childDir, nested.name)
      const nestedFiles = listSequence(nestedDir)
      const rel = nestedFiles.map((name) => `${child.name}/${nested.name}/${name}`)
      if (child.name === 'normals') {
        addClip(clips, nested.name, rel)
      } else {
        addClip(clips, `${child.name}__${nested.name}`, rel)
      }
    }
  }
  if (Object.keys(clips).length > 0) {
    index[fighter.name] = clips
  }
  if (Object.keys(fighterSheets).length > 0) {
    sheets[fighter.name] = fighterSheets
  }
}

fs.writeFileSync(outFile, `/** Generated by scripts/index-sprites.mjs. Do not edit by hand. */
export const SPRITE_CLIP_INDEX: Record<string, Record<string, string[]>> = ${JSON.stringify(index, null, 2)}
`)
fs.writeFileSync(sheetOut, `/** Generated by scripts/index-sprites.mjs. Do not edit by hand. */
export interface SpriteSheetClipMeta {
  file: string
  frameWidth: number
  frameHeight: number
  frames: number
  columns: number
  rows: number
  fps: number
  loop: boolean
  anchorX?: number
  anchorY?: number
}

export const SPRITE_SHEET_INDEX: Record<string, Record<string, SpriteSheetClipMeta>> = ${JSON.stringify(sheets, null, 2)}
`)
const fighters = Object.keys(index).length
const frames = Object.values(index).reduce((sum, clips) => sum + Object.values(clips).reduce((n, files) => n + files.length, 0), 0)
console.info(`[index-sprites] ${fighters} fighters, ${frames} frames -> ${path.relative(process.cwd(), outFile)}`)
