/** Generated by scripts/index-sprites.mjs. Do not edit by hand. */
export interface SpriteSheetClipMeta {
  file: string
  frameWidth: number
  frameHeight: number
  frames: number
  columns: number
  rows: number
  fps: number
  loop: boolean
  anchorX?: number
  anchorY?: number
}

export const SPRITE_SHEET_INDEX: Record<string, Record<string, SpriteSheetClipMeta>> = {}
