/** Generated by scripts/index-sprites.mjs. Do not edit by hand. */
export const SPRITE_CLIP_INDEX: Record<string, Record<string, string[]>> = {
  "benimaru": {
    "attack": [
      "attack/001.png",
      "attack/002.png",
      "attack/003.png",
      "attack/004.png",
      "attack/005.png",
      "attack/006.png",
      "attack/007.png",
      "attack/008.png"
    ],
    "block": [
      "block/001.png",
      "block/002.png",
      "block/003.png",
      "block/004.png",
      "block/005.png",
      "block/006.png"
    ],
    "dash": [
      "dash/001.png",
      "dash/002.png",
      "dash/003.png",
      "dash/004.png",
      "dash/005.png",
      "dash/006.png"
    ],
    "dead": [
      "dead/001.png",
      "dead/002.png",
      "dead/003.png",
      "dead/004.png",
      "dead/005.png",
      "dead/006.png",
      "dead/007.png",
      "dead/008.png"
    ],
    "fall": [
      "fall/001.png",
      "fall/002.png",
      "fall/003.png",
      "fall/004.png"
    ],
    "getup": [
      "getup/001.png",
      "getup/002.png"
    ],
    "hit": [
      "hit/001.png",
      "hit/002.png",
      "hit/003.png",
      "hit/004.png",
      "hit/005.png",
      "hit/006.png"
    ],
    "idle": [
      "idle/001.png",
      "idle/002.png",
      "idle/003.png",
      "idle/004.png",
      "idle/005.png",
      "idle/006.png",
      "idle/007.png",
      "idle/008.png"
    ],
    "jump": [
      "jump/001.png",
      "jump/002.png",
      "jump/003.png",
      "jump/004.png"
    ],
    "knockdown": [
      "knockdown/001.png",
      "knockdown/002.png",
      "knockdown/003.png",
      "knockdown/004.png",
      "knockdown/005.png",
      "knockdown/006.png"
    ],
    "run": [
      "run/001.png",
      "run/002.png",
      "run/003.png",
      "run/004.png",
      "run/005.png",
      "run/006.png",
      "run/007.png",
      "run/008.png"
    ],
    "skill": [
      "skill/001.png",
      "skill/002.png",
      "skill/003.png",
      "skill/004.png",
      "skill/005.png",
      "skill/006.png",
      "skill/007.png",
      "skill/008.png"
    ],
    "switch_in": [
      "switch_in/001.png",
      "switch_in/002.png",
      "switch_in/003.png",
      "switch_in/004.png",
      "switch_in/005.png",
      "switch_in/006.png"
    ],
    "switch_out": [
      "switch_out/001.png",
      "switch_out/002.png",
      "switch_out/003.png",
      "switch_out/004.png",
      "switch_out/005.png",
      "switch_out/006.png"
    ],
    "ultimate": [
      "ultimate/001.png",
      "ultimate/002.png",
      "ultimate/003.png",
      "ultimate/004.png",
      "ultimate/005.png",
      "ultimate/006.png",
      "ultimate/007.png",
      "ultimate/008.png"
    ],
    "walk": [
      "walk/001.png",
      "walk/002.png",
      "walk/003.png",
      "walk/004.png",
      "walk/005.png",
      "walk/006.png",
      "walk/007.png",
      "walk/008.png"
    ]
  },
  "diablo": {
    "attack": [
      "attack/001.png",
      "attack/002.png",
      "attack/003.png",
      "attack/004.png",
      "attack/005.png",
      "attack/006.png",
      "attack/007.png",
      "attack/008.png"
    ],
    "block": [
      "block/001.png",
      "block/002.png",
      "block/003.png",
      "block/004.png",
      "block/005.png",
      "block/006.png"
    ],
    "dash": [
      "dash/001.png",
      "dash/002.png",
      "dash/003.png",
      "dash/004.png",
      "dash/005.png",
      "dash/006.png"
    ],
    "dead": [
      "dead/001.png",
      "dead/002.png",
      "dead/003.png",
      "dead/004.png",
      "dead/005.png",
      "dead/006.png",
      "dead/007.png",
      "dead/008.png"
    ],
    "fall": [
      "fall/001.png",
      "fall/002.png",
      "fall/003.png",
      "fall/004.png"
    ],
    "getup": [
      "getup/001.png",
      "getup/002.png"
    ],
    "hit": [
      "hit/001.png",
      "hit/002.png",
      "hit/003.png",
      "hit/004.png",
      "hit/005.png",
      "hit/006.png"
    ],
    "idle": [
      "idle/001.png",
      "idle/002.png",
      "idle/003.png",
      "idle/004.png",
      "idle/005.png",
      "idle/006.png",
      "idle/007.png",
      "idle/008.png"
    ],
    "jump": [
      "jump/001.png",
      "jump/002.png",
      "jump/003.png",
      "jump/004.png"
    ],
    "knockdown": [
      "knockdown/001.png",
      "knockdown/002.png",
      "knockdown/003.png",
      "knockdown/004.png",
      "knockdown/005.png",
      "knockdown/006.png"
    ],
    "run": [
      "run/001.png",
      "run/002.png",
      "run/003.png",
      "run/004.png",
      "run/005.png",
      "run/006.png",
      "run/007.png",
      "run/008.png"
    ],
    "skill": [
      "skill/001.png",
      "skill/002.png",
      "skill/003.png",
      "skill/004.png",
      "skill/005.png",
      "skill/006.png",
      "skill/007.png",
      "skill/008.png"
    ],
    "switch_in": [
      "switch_in/001.png",
      "switch_in/002.png",
      "switch_in/003.png",
      "switch_in/004.png",
      "switch_in/005.png",
      "switch_in/006.png"
    ],
    "switch_out": [
      "switch_out/001.png",
      "switch_out/002.png",
      "switch_out/003.png",
      "switch_out/004.png",
      "switch_out/005.png",
      "switch_out/006.png"
    ],
    "ultimate": [
      "ultimate/001.png",
      "ultimate/002.png",
      "ultimate/003.png",
      "ultimate/004.png",
      "ultimate/005.png",
      "ultimate/006.png",
      "ultimate/007.png",
      "ultimate/008.png"
    ],
    "walk": [
      "walk/001.png",
      "walk/002.png",
      "walk/003.png",
      "walk/004.png",
      "walk/005.png",
      "walk/006.png",
      "walk/007.png",
      "walk/008.png"
    ]
  },
  "guy": {
    "attack": [
      "attack/001.png",
      "attack/002.png",
      "attack/003.png",
      "attack/004.png",
      "attack/005.png",
      "attack/006.png",
      "attack/007.png",
      "attack/008.png"
    ],
    "block": [
      "block/001.png",
      "block/002.png",
      "block/003.png",
      "block/004.png",
      "block/005.png",
      "block/006.png"
    ],
    "dash": [
      "dash/001.png",
      "dash/002.png",
      "dash/003.png",
      "dash/004.png",
      "dash/005.png",
      "dash/006.png"
    ],
    "dead": [
      "dead/001.png",
      "dead/002.png",
      "dead/003.png",
      "dead/004.png",
      "dead/005.png",
      "dead/006.png",
      "dead/007.png",
      "dead/008.png"
    ],
    "fall": [
      "fall/001.png",
      "fall/002.png",
      "fall/003.png",
      "fall/004.png"
    ],
    "getup": [
      "getup/001.png",
      "getup/002.png"
    ],
    "hit": [
      "hit/001.png",
      "hit/002.png",
      "hit/003.png",
      "hit/004.png",
      "hit/005.png",
      "hit/006.png"
    ],
    "idle": [
      "idle/001.png",
      "idle/002.png",
      "idle/003.png",
      "idle/004.png",
      "idle/005.png",
      "idle/006.png",
      "idle/007.png",
      "idle/008.png"
    ],
    "jump": [
      "jump/001.png",
      "jump/002.png",
      "jump/003.png",
      "jump/004.png"
    ],
    "knockdown": [
      "knockdown/001.png",
      "knockdown/002.png",
      "knockdown/003.png",
      "knockdown/004.png",
      "knockdown/005.png",
      "knockdown/006.png"
    ],
    "run": [
      "run/001.png",
      "run/002.png",
      "run/003.png",
      "run/004.png",
      "run/005.png",
      "run/006.png",
      "run/007.png",
      "run/008.png"
    ],
    "skill": [
      "skill/001.png",
      "skill/002.png",
      "skill/003.png",
      "skill/004.png",
      "skill/005.png",
      "skill/006.png",
      "skill/007.png",
      "skill/008.png"
    ],
    "switch_in": [
      "switch_in/001.png",
      "switch_in/002.png",
      "switch_in/003.png",
      "switch_in/004.png",
      "switch_in/005.png",
      "switch_in/006.png"
    ],
    "switch_out": [
      "switch_out/001.png",
      "switch_out/002.png",
      "switch_out/003.png",
      "switch_out/004.png",
      "switch_out/005.png",
      "switch_out/006.png"
    ],
    "ultimate": [
      "ultimate/001.png",
      "ultimate/002.png",
      "ultimate/003.png",
      "ultimate/004.png",
      "ultimate/005.png",
      "ultimate/006.png",
      "ultimate/007.png",
      "ultimate/008.png"
    ],
    "walk": [
      "walk/001.png",
      "walk/002.png",
      "walk/003.png",
      "walk/004.png",
      "walk/005.png",
      "walk/006.png",
      "walk/007.png",
      "walk/008.png"
    ]
  },
  "hakurou": {
    "attack": [
      "attack/001.png",
      "attack/002.png",
      "attack/003.png",
      "attack/004.png",
      "attack/005.png",
      "attack/006.png",
      "attack/007.png",
      "attack/008.png"
    ],
    "block": [
      "block/001.png",
      "block/002.png",
      "block/003.png",
      "block/004.png",
      "block/005.png",
      "block/006.png"
    ],
    "dash": [
      "dash/001.png",
      "dash/002.png",
      "dash/003.png",
      "dash/004.png",
      "dash/005.png",
      "dash/006.png"
    ],
    "dead": [
      "dead/001.png",
      "dead/002.png",
      "dead/003.png",
      "dead/004.png",
      "dead/005.png",
      "dead/006.png",
      "dead/007.png",
      "dead/008.png"
    ],
    "fall": [
      "fall/001.png",
      "fall/002.png",
      "fall/003.png",
      "fall/004.png"
    ],
    "getup": [
      "getup/001.png",
      "getup/002.png"
    ],
    "hit": [
      "hit/001.png",
      "hit/002.png",
      "hit/003.png",
      "hit/004.png",
      "hit/005.png",
      "hit/006.png"
    ],
    "idle": [
      "idle/001.png",
      "idle/002.png",
      "idle/003.png",
      "idle/004.png",
      "idle/005.png",
      "idle/006.png",
      "idle/007.png",
      "idle/008.png"
    ],
    "jump": [
      "jump/001.png",
      "jump/002.png",
      "jump/003.png",
      "jump/004.png"
    ],
    "knockdown": [
      "knockdown/001.png",
      "knockdown/002.png",
      "knockdown/003.png",
      "knockdown/004.png",
      "knockdown/005.png",
      "knockdown/006.png"
    ],
    "run": [
      "run/001.png",
      "run/002.png",
      "run/003.png",
      "run/004.png",
      "run/005.png",
      "run/006.png",
      "run/007.png",
      "run/008.png"
    ],
    "skill": [
      "skill/001.png",
      "skill/002.png",
      "skill/003.png",
      "skill/004.png",
      "skill/005.png",
      "skill/006.png",
      "skill/007.png",
      "skill/008.png"
    ],
    "switch_in": [
      "switch_in/001.png",
      "switch_in/002.png",
      "switch_in/003.png",
      "switch_in/004.png",
      "switch_in/005.png",
      "switch_in/006.png"
    ],
    "switch_out": [
      "switch_out/001.png",
      "switch_out/002.png",
      "switch_out/003.png",
      "switch_out/004.png",
      "switch_out/005.png",
      "switch_out/006.png"
    ],
    "ultimate": [
      "ultimate/001.png",
      "ultimate/002.png",
      "ultimate/003.png",
      "ultimate/004.png",
      "ultimate/005.png",
      "ultimate/006.png",
      "ultimate/007.png",
      "ultimate/008.png"
    ],
    "walk": [
      "walk/001.png",
      "walk/002.png",
      "walk/003.png",
      "walk/004.png",
      "walk/005.png",
      "walk/006.png",
      "walk/007.png",
      "walk/008.png"
    ]
  },
  "hinata": {
    "attack": [
      "attack/001.png",
      "attack/002.png",
      "attack/003.png",
      "attack/004.png",
      "attack/005.png",
      "attack/006.png",
      "attack/007.png",
      "attack/008.png"
    ],
    "block": [
      "block/001.png",
      "block/002.png",
      "block/003.png",
      "block/004.png",
      "block/005.png",
      "block/006.png"
    ],
    "dash": [
      "dash/001.png",
      "dash/002.png",
      "dash/003.png",
      "dash/004.png",
      "dash/005.png",
      "dash/006.png"
    ],
    "dead": [
      "dead/001.png",
      "dead/002.png",
      "dead/003.png",
      "dead/004.png",
      "dead/005.png",
      "dead/006.png",
      "dead/007.png",
      "dead/008.png"
    ],
    "fall": [
      "fall/001.png",
      "fall/002.png",
      "fall/003.png",
      "fall/004.png"
    ],
    "getup": [
      "getup/001.png",
      "getup/002.png"
    ],
    "hit": [
      "hit/001.png",
      "hit/002.png",
      "hit/003.png",
      "hit/004.png",
      "hit/005.png",
      "hit/006.png"
    ],
    "idle": [
      "idle/001.png",
      "idle/002.png",
      "idle/003.png",
      "idle/004.png",
      "idle/005.png",
      "idle/006.png",
      "idle/007.png",
      "idle/008.png"
    ],
    "jump": [
      "jump/001.png",
      "jump/002.png",
      "jump/003.png",
      "jump/004.png"
    ],
    "knockdown": [
      "knockdown/001.png",
      "knockdown/002.png",
      "knockdown/003.png",
      "knockdown/004.png",
      "knockdown/005.png",
      "knockdown/006.png"
    ],
    "run": [
      "run/001.png",
      "run/002.png",
      "run/003.png",
      "run/004.png",
      "run/005.png",
      "run/006.png",
      "run/007.png",
      "run/008.png"
    ],
    "skill": [
      "skill/001.png",
      "skill/002.png",
      "skill/003.png",
      "skill/004.png",
      "skill/005.png",
      "skill/006.png",
      "skill/007.png",
      "skill/008.png"
    ],
    "switch_in": [
      "switch_in/001.png",
      "switch_in/002.png",
      "switch_in/003.png",
      "switch_in/004.png",
      "switch_in/005.png",
      "switch_in/006.png"
    ],
    "switch_out": [
      "switch_out/001.png",
      "switch_out/002.png",
      "switch_out/003.png",
      "switch_out/004.png",
      "switch_out/005.png",
      "switch_out/006.png"
    ],
    "ultimate": [
      "ultimate/001.png",
      "ultimate/002.png",
      "ultimate/003.png",
      "ultimate/004.png",
      "ultimate/005.png",
      "ultimate/006.png",
      "ultimate/007.png",
      "ultimate/008.png"
    ],
    "walk": [
      "walk/001.png",
      "walk/002.png",
      "walk/003.png",
      "walk/004.png",
      "walk/005.png",
      "walk/006.png",
      "walk/007.png",
      "walk/008.png"
    ]
  },
  "milim": {
    "attack": [
      "attack/001.png",
      "attack/002.png",
      "attack/003.png",
      "attack/004.png",
      "attack/005.png",
      "attack/006.png",
      "attack/007.png",
      "attack/008.png"
    ],
    "block": [
      "block/001.png",
      "block/002.png",
      "block/003.png",
      "block/004.png",
      "block/005.png",
      "block/006.png"
    ],
    "dash": [
      "dash/001.png",
      "dash/002.png",
      "dash/003.png",
      "dash/004.png",
      "dash/005.png",
      "dash/006.png"
    ],
    "dead": [
      "dead/001.png",
      "dead/002.png",
      "dead/003.png",
      "dead/004.png",
      "dead/005.png",
      "dead/006.png",
      "dead/007.png",
      "dead/008.png"
    ],
    "fall": [
      "fall/001.png",
      "fall/002.png",
      "fall/003.png",
      "fall/004.png"
    ],
    "getup": [
      "getup/001.png",
      "getup/002.png"
    ],
    "hit": [
      "hit/001.png",
      "hit/002.png",
      "hit/003.png",
      "hit/004.png",
      "hit/005.png",
      "hit/006.png"
    ],
    "idle": [
      "idle/001.png",
      "idle/002.png",
      "idle/003.png",
      "idle/004.png",
      "idle/005.png",
      "idle/006.png",
      "idle/007.png",
      "idle/008.png"
    ],
    "jump": [
      "jump/001.png",
      "jump/002.png",
      "jump/003.png",
      "jump/004.png"
    ],
    "knockdown": [
      "knockdown/001.png",
      "knockdown/002.png",
      "knockdown/003.png",
      "knockdown/004.png",
      "knockdown/005.png",
      "knockdown/006.png"
    ],
    "run": [
      "run/001.png",
      "run/002.png",
      "run/003.png",
      "run/004.png",
      "run/005.png",
      "run/006.png",
      "run/007.png",
      "run/008.png"
    ],
    "skill": [
      "skill/001.png",
      "skill/002.png",
      "skill/003.png",
      "skill/004.png",
      "skill/005.png",
      "skill/006.png",
      "skill/007.png",
      "skill/008.png"
    ],
    "switch_in": [
      "switch_in/001.png",
      "switch_in/002.png",
      "switch_in/003.png",
      "switch_in/004.png",
      "switch_in/005.png",
      "switch_in/006.png"
    ],
    "switch_out": [
      "switch_out/001.png",
      "switch_out/002.png",
      "switch_out/003.png",
      "switch_out/004.png",
      "switch_out/005.png",
      "switch_out/006.png"
    ],
    "ultimate": [
      "ultimate/001.png",
      "ultimate/002.png",
      "ultimate/003.png",
      "ultimate/004.png",
      "ultimate/005.png",
      "ultimate/006.png",
      "ultimate/007.png",
      "ultimate/008.png"
    ],
    "walk": [
      "walk/001.png",
      "walk/002.png",
      "walk/003.png",
      "walk/004.png",
      "walk/005.png",
      "walk/006.png",
      "walk/007.png",
      "walk/008.png"
    ]
  },
  "rimuru": {
    "attack": [
      "attack/001.png",
      "attack/002.png",
      "attack/003.png",
      "attack/004.png",
      "attack/005.png",
      "attack/006.png",
      "attack/007.png",
      "attack/008.png",
      "attack/009.png",
      "attack/010.png",
      "attack/011.png",
      "attack/012.png"
    ],
    "block": [
      "block/001.png",
      "block/002.png",
      "block/003.png",
      "block/004.png",
      "block/005.png",
      "block/006.png"
    ],
    "dash": [
      "dash/001.png",
      "dash/002.png",
      "dash/003.png",
      "dash/004.png",
      "dash/005.png",
      "dash/006.png"
    ],
    "dead": [
      "dead/001.png",
      "dead/002.png",
      "dead/003.png",
      "dead/004.png",
      "dead/005.png",
      "dead/006.png",
      "dead/007.png",
      "dead/008.png"
    ],
    "fall": [
      "fall/001.png",
      "fall/002.png",
      "fall/003.png",
      "fall/004.png"
    ],
    "getup": [
      "getup/001.png",
      "getup/002.png"
    ],
    "hit": [
      "hit/001.png",
      "hit/002.png",
      "hit/003.png",
      "hit/004.png",
      "hit/005.png",
      "hit/006.png"
    ],
    "idle": [
      "idle/001.png",
      "idle/002.png",
      "idle/003.png",
      "idle/004.png",
      "idle/005.png",
      "idle/006.png",
      "idle/007.png",
      "idle/008.png"
    ],
    "jump": [
      "jump/001.png",
      "jump/002.png",
      "jump/003.png",
      "jump/004.png"
    ],
    "knockdown": [
      "knockdown/001.png",
      "knockdown/002.png",
      "knockdown/003.png",
      "knockdown/004.png",
      "knockdown/005.png",
      "knockdown/006.png"
    ],
    "rimuru-shizu__rimuru_black_lightning": [
      "rimuru-shizu/rimuru_black_lightning/001.png",
      "rimuru-shizu/rimuru_black_lightning/002.png",
      "rimuru-shizu/rimuru_black_lightning/003.png",
      "rimuru-shizu/rimuru_black_lightning/004.png",
      "rimuru-shizu/rimuru_black_lightning/005.png",
      "rimuru-shizu/rimuru_black_lightning/006.png",
      "rimuru-shizu/rimuru_black_lightning/007.png",
      "rimuru-shizu/rimuru_black_lightning/008.png",
      "rimuru-shizu/rimuru_black_lightning/009.png",
      "rimuru-shizu/rimuru_black_lightning/010.png",
      "rimuru-shizu/rimuru_black_lightning/011.png",
      "rimuru-shizu/rimuru_black_lightning/012.png",
      "rimuru-shizu/rimuru_black_lightning/013.png",
      "rimuru-shizu/rimuru_black_lightning/014.png",
      "rimuru-shizu/rimuru_black_lightning/015.png",
      "rimuru-shizu/rimuru_black_lightning/016.png",
      "rimuru-shizu/rimuru_black_lightning/017.png",
      "rimuru-shizu/rimuru_black_lightning/018.png",
      "rimuru-shizu/rimuru_black_lightning/019.png",
      "rimuru-shizu/rimuru_black_lightning/020.png",
      "rimuru-shizu/rimuru_black_lightning/021.png",
      "rimuru-shizu/rimuru_black_lightning/022.png",
      "rimuru-shizu/rimuru_black_lightning/023.png",
      "rimuru-shizu/rimuru_black_lightning/024.png",
      "rimuru-shizu/rimuru_black_lightning/025.png",
      "rimuru-shizu/rimuru_black_lightning/026.png",
      "rimuru-shizu/rimuru_black_lightning/027.png",
      "rimuru-shizu/rimuru_black_lightning/028.png",
      "rimuru-shizu/rimuru_black_lightning/029.png",
      "rimuru-shizu/rimuru_black_lightning/030.png",
      "rimuru-shizu/rimuru_black_lightning/031.png",
      "rimuru-shizu/rimuru_black_lightning/032.png"
    ],
    "rimuru-shizu__rimuru_predator": [
      "rimuru-shizu/rimuru_predator/001.png",
      "rimuru-shizu/rimuru_predator/002.png",
      "rimuru-shizu/rimuru_predator/003.png",
      "rimuru-shizu/rimuru_predator/004.png",
      "rimuru-shizu/rimuru_predator/005.png",
      "rimuru-shizu/rimuru_predator/006.png",
      "rimuru-shizu/rimuru_predator/007.png",
      "rimuru-shizu/rimuru_predator/008.png",
      "rimuru-shizu/rimuru_predator/009.png",
      "rimuru-shizu/rimuru_predator/010.png",
      "rimuru-shizu/rimuru_predator/011.png",
      "rimuru-shizu/rimuru_predator/012.png",
      "rimuru-shizu/rimuru_predator/013.png",
      "rimuru-shizu/rimuru_predator/014.png",
      "rimuru-shizu/rimuru_predator/015.png",
      "rimuru-shizu/rimuru_predator/016.png",
      "rimuru-shizu/rimuru_predator/017.png",
      "rimuru-shizu/rimuru_predator/018.png",
      "rimuru-shizu/rimuru_predator/019.png",
      "rimuru-shizu/rimuru_predator/020.png",
      "rimuru-shizu/rimuru_predator/021.png",
      "rimuru-shizu/rimuru_predator/022.png",
      "rimuru-shizu/rimuru_predator/023.png",
      "rimuru-shizu/rimuru_predator/024.png",
      "rimuru-shizu/rimuru_predator/025.png",
      "rimuru-shizu/rimuru_predator/026.png",
      "rimuru-shizu/rimuru_predator/027.png",
      "rimuru-shizu/rimuru_predator/028.png",
      "rimuru-shizu/rimuru_predator/029.png",
      "rimuru-shizu/rimuru_predator/030.png",
      "rimuru-shizu/rimuru_predator/031.png",
      "rimuru-shizu/rimuru_predator/032.png",
      "rimuru-shizu/rimuru_predator/033.png",
      "rimuru-shizu/rimuru_predator/034.png",
      "rimuru-shizu/rimuru_predator/035.png",
      "rimuru-shizu/rimuru_predator/036.png"
    ],
    "rimuru-shizu__rimuru_water_blade": [
      "rimuru-shizu/rimuru_water_blade/001.png",
      "rimuru-shizu/rimuru_water_blade/002.png",
      "rimuru-shizu/rimuru_water_blade/003.png",
      "rimuru-shizu/rimuru_water_blade/004.png",
      "rimuru-shizu/rimuru_water_blade/005.png",
      "rimuru-shizu/rimuru_water_blade/006.png",
      "rimuru-shizu/rimuru_water_blade/007.png",
      "rimuru-shizu/rimuru_water_blade/008.png",
      "rimuru-shizu/rimuru_water_blade/009.png",
      "rimuru-shizu/rimuru_water_blade/010.png",
      "rimuru-shizu/rimuru_water_blade/011.png",
      "rimuru-shizu/rimuru_water_blade/012.png",
      "rimuru-shizu/rimuru_water_blade/013.png",
      "rimuru-shizu/rimuru_water_blade/014.png",
      "rimuru-shizu/rimuru_water_blade/015.png",
      "rimuru-shizu/rimuru_water_blade/016.png",
      "rimuru-shizu/rimuru_water_blade/017.png",
      "rimuru-shizu/rimuru_water_blade/018.png",
      "rimuru-shizu/rimuru_water_blade/019.png",
      "rimuru-shizu/rimuru_water_blade/020.png",
      "rimuru-shizu/rimuru_water_blade/021.png",
      "rimuru-shizu/rimuru_water_blade/022.png",
      "rimuru-shizu/rimuru_water_blade/023.png",
      "rimuru-shizu/rimuru_water_blade/024.png",
      "rimuru-shizu/rimuru_water_blade/025.png",
      "rimuru-shizu/rimuru_water_blade/026.png",
      "rimuru-shizu/rimuru_water_blade/027.png",
      "rimuru-shizu/rimuru_water_blade/028.png"
    ],
    "run": [
      "run/001.png",
      "run/002.png",
      "run/003.png",
      "run/004.png",
      "run/005.png",
      "run/006.png",
      "run/007.png",
      "run/008.png"
    ],
    "skill": [
      "skill/001.png",
      "skill/002.png",
      "skill/003.png",
      "skill/004.png",
      "skill/005.png",
      "skill/006.png",
      "skill/007.png",
      "skill/008.png"
    ],
    "switch_in": [
      "switch_in/001.png",
      "switch_in/002.png",
      "switch_in/003.png",
      "switch_in/004.png",
      "switch_in/005.png",
      "switch_in/006.png"
    ],
    "switch_out": [
      "switch_out/001.png",
      "switch_out/002.png",
      "switch_out/003.png",
      "switch_out/004.png",
      "switch_out/005.png",
      "switch_out/006.png"
    ],
    "ultimate": [
      "ultimate/001.png",
      "ultimate/002.png",
      "ultimate/003.png",
      "ultimate/004.png",
      "ultimate/005.png",
      "ultimate/006.png",
      "ultimate/007.png",
      "ultimate/008.png"
    ],
    "walk": [
      "walk/001.png",
      "walk/002.png",
      "walk/003.png",
      "walk/004.png",
      "walk/005.png",
      "walk/006.png",
      "walk/007.png",
      "walk/008.png"
    ]
  },
  "shion": {
    "attack": [
      "attack/001.png",
      "attack/002.png",
      "attack/003.png",
      "attack/004.png",
      "attack/005.png",
      "attack/006.png",
      "attack/007.png",
      "attack/008.png"
    ],
    "block": [
      "block/001.png",
      "block/002.png",
      "block/003.png",
      "block/004.png",
      "block/005.png",
      "block/006.png"
    ],
    "dash": [
      "dash/001.png",
      "dash/002.png",
      "dash/003.png",
      "dash/004.png",
      "dash/005.png",
      "dash/006.png"
    ],
    "dead": [
      "dead/001.png",
      "dead/002.png",
      "dead/003.png",
      "dead/004.png",
      "dead/005.png",
      "dead/006.png",
      "dead/007.png",
      "dead/008.png"
    ],
    "fall": [
      "fall/001.png",
      "fall/002.png",
      "fall/003.png",
      "fall/004.png"
    ],
    "getup": [
      "getup/001.png",
      "getup/002.png"
    ],
    "hit": [
      "hit/001.png",
      "hit/002.png",
      "hit/003.png",
      "hit/004.png",
      "hit/005.png",
      "hit/006.png"
    ],
    "idle": [
      "idle/001.png",
      "idle/002.png",
      "idle/003.png",
      "idle/004.png",
      "idle/005.png",
      "idle/006.png",
      "idle/007.png",
      "idle/008.png"
    ],
    "jump": [
      "jump/001.png",
      "jump/002.png",
      "jump/003.png",
      "jump/004.png"
    ],
    "knockdown": [
      "knockdown/001.png",
      "knockdown/002.png",
      "knockdown/003.png",
      "knockdown/004.png",
      "knockdown/005.png",
      "knockdown/006.png"
    ],
    "run": [
      "run/001.png",
      "run/002.png",
      "run/003.png",
      "run/004.png",
      "run/005.png",
      "run/006.png",
      "run/007.png",
      "run/008.png"
    ],
    "skill": [
      "skill/001.png",
      "skill/002.png",
      "skill/003.png",
      "skill/004.png",
      "skill/005.png",
      "skill/006.png",
      "skill/007.png",
      "skill/008.png"
    ],
    "switch_in": [
      "switch_in/001.png",
      "switch_in/002.png",
      "switch_in/003.png",
      "switch_in/004.png",
      "switch_in/005.png",
      "switch_in/006.png"
    ],
    "switch_out": [
      "switch_out/001.png",
      "switch_out/002.png",
      "switch_out/003.png",
      "switch_out/004.png",
      "switch_out/005.png",
      "switch_out/006.png"
    ],
    "ultimate": [
      "ultimate/001.png",
      "ultimate/002.png",
      "ultimate/003.png",
      "ultimate/004.png",
      "ultimate/005.png",
      "ultimate/006.png",
      "ultimate/007.png",
      "ultimate/008.png"
    ],
    "walk": [
      "walk/001.png",
      "walk/002.png",
      "walk/003.png",
      "walk/004.png",
      "walk/005.png",
      "walk/006.png",
      "walk/007.png",
      "walk/008.png"
    ]
  },
  "shuna": {
    "attack": [
      "attack/001.png",
      "attack/002.png",
      "attack/003.png",
      "attack/004.png",
      "attack/005.png",
      "attack/006.png",
      "attack/007.png",
      "attack/008.png"
    ],
    "block": [
      "block/001.png",
      "block/002.png",
      "block/003.png",
      "block/004.png",
      "block/005.png",
      "block/006.png"
    ],
    "dash": [
      "dash/001.png",
      "dash/002.png",
      "dash/003.png",
      "dash/004.png",
      "dash/005.png",
      "dash/006.png"
    ],
    "dead": [
      "dead/001.png",
      "dead/002.png",
      "dead/003.png",
      "dead/004.png",
      "dead/005.png",
      "dead/006.png",
      "dead/007.png",
      "dead/008.png"
    ],
    "fall": [
      "fall/001.png",
      "fall/002.png",
      "fall/003.png",
      "fall/004.png"
    ],
    "getup": [
      "getup/001.png",
      "getup/002.png"
    ],
    "hit": [
      "hit/001.png",
      "hit/002.png",
      "hit/003.png",
      "hit/004.png",
      "hit/005.png",
      "hit/006.png"
    ],
    "idle": [
      "idle/001.png",
      "idle/002.png",
      "idle/003.png",
      "idle/004.png",
      "idle/005.png",
      "idle/006.png",
      "idle/007.png",
      "idle/008.png"
    ],
    "jump": [
      "jump/001.png",
      "jump/002.png",
      "jump/003.png",
      "jump/004.png"
    ],
    "knockdown": [
      "knockdown/001.png",
      "knockdown/002.png",
      "knockdown/003.png",
      "knockdown/004.png",
      "knockdown/005.png",
      "knockdown/006.png"
    ],
    "run": [
      "run/001.png",
      "run/002.png",
      "run/003.png",
      "run/004.png",
      "run/005.png",
      "run/006.png",
      "run/007.png",
      "run/008.png"
    ],
    "skill": [
      "skill/001.png",
      "skill/002.png",
      "skill/003.png",
      "skill/004.png",
      "skill/005.png",
      "skill/006.png",
      "skill/007.png",
      "skill/008.png"
    ],
    "switch_in": [
      "switch_in/001.png",
      "switch_in/002.png",
      "switch_in/003.png",
      "switch_in/004.png",
      "switch_in/005.png",
      "switch_in/006.png"
    ],
    "switch_out": [
      "switch_out/001.png",
      "switch_out/002.png",
      "switch_out/003.png",
      "switch_out/004.png",
      "switch_out/005.png",
      "switch_out/006.png"
    ],
    "ultimate": [
      "ultimate/001.png",
      "ultimate/002.png",
      "ultimate/003.png",
      "ultimate/004.png",
      "ultimate/005.png",
      "ultimate/006.png",
      "ultimate/007.png",
      "ultimate/008.png"
    ],
    "walk": [
      "walk/001.png",
      "walk/002.png",
      "walk/003.png",
      "walk/004.png",
      "walk/005.png",
      "walk/006.png",
      "walk/007.png",
      "walk/008.png"
    ]
  },
  "souei": {
    "attack": [
      "attack/001.png",
      "attack/002.png",
      "attack/003.png",
      "attack/004.png",
      "attack/005.png",
      "attack/006.png",
      "attack/007.png",
      "attack/008.png"
    ],
    "block": [
      "block/001.png",
      "block/002.png",
      "block/003.png",
      "block/004.png",
      "block/005.png",
      "block/006.png"
    ],
    "dash": [
      "dash/001.png",
      "dash/002.png",
      "dash/003.png",
      "dash/004.png",
      "dash/005.png",
      "dash/006.png"
    ],
    "dead": [
      "dead/001.png",
      "dead/002.png",
      "dead/003.png",
      "dead/004.png",
      "dead/005.png",
      "dead/006.png",
      "dead/007.png",
      "dead/008.png"
    ],
    "fall": [
      "fall/001.png",
      "fall/002.png",
      "fall/003.png",
      "fall/004.png"
    ],
    "getup": [
      "getup/001.png",
      "getup/002.png"
    ],
    "hit": [
      "hit/001.png",
      "hit/002.png",
      "hit/003.png",
      "hit/004.png",
      "hit/005.png",
      "hit/006.png"
    ],
    "idle": [
      "idle/001.png",
      "idle/002.png",
      "idle/003.png",
      "idle/004.png",
      "idle/005.png",
      "idle/006.png",
      "idle/007.png",
      "idle/008.png"
    ],
    "jump": [
      "jump/001.png",
      "jump/002.png",
      "jump/003.png",
      "jump/004.png"
    ],
    "knockdown": [
      "knockdown/001.png",
      "knockdown/002.png",
      "knockdown/003.png",
      "knockdown/004.png",
      "knockdown/005.png",
      "knockdown/006.png"
    ],
    "run": [
      "run/001.png",
      "run/002.png",
      "run/003.png",
      "run/004.png",
      "run/005.png",
      "run/006.png",
      "run/007.png",
      "run/008.png"
    ],
    "skill": [
      "skill/001.png",
      "skill/002.png",
      "skill/003.png",
      "skill/004.png",
      "skill/005.png",
      "skill/006.png",
      "skill/007.png",
      "skill/008.png"
    ],
    "switch_in": [
      "switch_in/001.png",
      "switch_in/002.png",
      "switch_in/003.png",
      "switch_in/004.png",
      "switch_in/005.png",
      "switch_in/006.png"
    ],
    "switch_out": [
      "switch_out/001.png",
      "switch_out/002.png",
      "switch_out/003.png",
      "switch_out/004.png",
      "switch_out/005.png",
      "switch_out/006.png"
    ],
    "ultimate": [
      "ultimate/001.png",
      "ultimate/002.png",
      "ultimate/003.png",
      "ultimate/004.png",
      "ultimate/005.png",
      "ultimate/006.png",
      "ultimate/007.png",
      "ultimate/008.png"
    ],
    "walk": [
      "walk/001.png",
      "walk/002.png",
      "walk/003.png",
      "walk/004.png",
      "walk/005.png",
      "walk/006.png",
      "walk/007.png",
      "walk/008.png"
    ]
  },
  "veldora": {
    "attack": [
      "attack/001.png",
      "attack/002.png",
      "attack/003.png",
      "attack/004.png",
      "attack/005.png",
      "attack/006.png",
      "attack/007.png",
      "attack/008.png"
    ],
    "block": [
      "block/001.png",
      "block/002.png",
      "block/003.png",
      "block/004.png",
      "block/005.png",
      "block/006.png"
    ],
    "dash": [
      "dash/001.png",
      "dash/002.png",
      "dash/003.png",
      "dash/004.png",
      "dash/005.png",
      "dash/006.png"
    ],
    "dead": [
      "dead/001.png",
      "dead/002.png",
      "dead/003.png",
      "dead/004.png",
      "dead/005.png",
      "dead/006.png",
      "dead/007.png",
      "dead/008.png"
    ],
    "fall": [
      "fall/001.png",
      "fall/002.png",
      "fall/003.png",
      "fall/004.png"
    ],
    "getup": [
      "getup/001.png",
      "getup/002.png"
    ],
    "hit": [
      "hit/001.png",
      "hit/002.png",
      "hit/003.png",
      "hit/004.png",
      "hit/005.png",
      "hit/006.png"
    ],
    "idle": [
      "idle/001.png",
      "idle/002.png",
      "idle/003.png",
      "idle/004.png",
      "idle/005.png",
      "idle/006.png",
      "idle/007.png",
      "idle/008.png"
    ],
    "jump": [
      "jump/001.png",
      "jump/002.png",
      "jump/003.png",
      "jump/004.png"
    ],
    "knockdown": [
      "knockdown/001.png",
      "knockdown/002.png",
      "knockdown/003.png",
      "knockdown/004.png",
      "knockdown/005.png",
      "knockdown/006.png"
    ],
    "run": [
      "run/001.png",
      "run/002.png",
      "run/003.png",
      "run/004.png",
      "run/005.png",
      "run/006.png",
      "run/007.png",
      "run/008.png"
    ],
    "skill": [
      "skill/001.png",
      "skill/002.png",
      "skill/003.png",
      "skill/004.png",
      "skill/005.png",
      "skill/006.png",
      "skill/007.png",
      "skill/008.png"
    ],
    "switch_in": [
      "switch_in/001.png",
      "switch_in/002.png",
      "switch_in/003.png",
      "switch_in/004.png",
      "switch_in/005.png",
      "switch_in/006.png"
    ],
    "switch_out": [
      "switch_out/001.png",
      "switch_out/002.png",
      "switch_out/003.png",
      "switch_out/004.png",
      "switch_out/005.png",
      "switch_out/006.png"
    ],
    "ultimate": [
      "ultimate/001.png",
      "ultimate/002.png",
      "ultimate/003.png",
      "ultimate/004.png",
      "ultimate/005.png",
      "ultimate/006.png",
      "ultimate/007.png",
      "ultimate/008.png"
    ],
    "walk": [
      "walk/001.png",
      "walk/002.png",
      "walk/003.png",
      "walk/004.png",
      "walk/005.png",
      "walk/006.png",
      "walk/007.png",
      "walk/008.png"
    ]
  }
}
