import { PveProfile, StorySource, type PveEnemyDef } from '../types.ts'
import { AttackKind, type AttackData } from '../../combat/Attack.ts'

export const PVE_ENEMIES: Record<string, PveEnemyDef> = {
  giant_bat: {
    id: 'giant_bat',
    name: 'Chauve-souris géante',
    species: 'Giant Bat',
    source: StorySource.ANIME,
    hp: 55,
    damage: 9,
    defense: 2,
    speed: 210,
    knockback: 120,
    profile: PveProfile.SWARM,
    tint: 0x4a3728,
    width: 72,
    height: 48,
    asset: 'TODO_ASSET',
  },
  evil_centipede: {
    id: 'evil_centipede',
    name: 'Mille-pattes maléfique',
    species: 'Evil Centipede',
    source: StorySource.LN,
    hp: 220,
    damage: 28,
    defense: 8,
    speed: 140,
    knockback: 200,
    profile: PveProfile.AGGRESSIVE,
    tint: 0x2e7d32,
    width: 140,
    height: 36,
    asset: 'TODO_ASSET',
  },
  cave_spider: {
    id: 'cave_spider',
    name: 'Araignée des cavernes',
    species: 'Cave Spider',
    source: StorySource.LN,
    hp: 120,
    damage: 22,
    defense: 6,
    speed: 180,
    knockback: 160,
    profile: PveProfile.DEFENSIVE,
    tint: 0x3e2723,
    width: 90,
    height: 52,
    asset: 'TODO_ASSET',
  },
  direwolf: {
    id: 'direwolf',
    name: 'Loup de la tempête',
    species: 'Direwolf',
    source: StorySource.LN,
    hp: 160,
    damage: 24,
    defense: 6,
    speed: 250,
    knockback: 220,
    profile: PveProfile.AGGRESSIVE,
    tint: 0x546e7a,
    width: 100,
    height: 64,
    asset: 'TODO_ASSET',
  },
  orc_soldier: {
    id: 'orc_soldier',
    name: 'Soldat orc',
    species: 'Orc',
    source: StorySource.LN,
    hp: 150,
    damage: 22,
    defense: 8,
    speed: 150,
    knockback: 180,
    profile: PveProfile.SWARM,
    tint: 0x6b4f2a,
    width: 86,
    height: 110,
    asset: 'TODO_ASSET',
  },
  orc_raider: {
    id: 'orc_raider',
    name: 'Orc assaillant',
    species: 'Orc',
    source: StorySource.LN,
    hp: 230,
    damage: 30,
    defense: 12,
    speed: 130,
    knockback: 240,
    profile: PveProfile.AGGRESSIVE,
    tint: 0x4e342e,
    width: 110,
    height: 128,
    asset: 'TODO_ASSET',
  },
  orc_disaster: {
    id: 'orc_disaster',
    name: 'Seigneur Orc',
    species: 'Orc Disaster',
    source: StorySource.LN,
    hp: 720,
    damage: 34,
    defense: 14,
    speed: 110,
    knockback: 80,
    profile: PveProfile.BOSS,
    tint: 0x3e2723,
    width: 200,
    height: 180,
    asset: 'TODO_ASSET',
  },
  falmuth_soldier: {
    id: 'falmuth_soldier',
    name: 'Soldat de Farmus',
    species: 'Human',
    source: StorySource.LN,
    hp: 130,
    damage: 20,
    defense: 7,
    speed: 170,
    knockback: 160,
    profile: PveProfile.SWARM,
    tint: 0x5d4037,
    width: 70,
    height: 108,
    asset: 'TODO_ASSET',
  },
  falmuth_knight: {
    id: 'falmuth_knight',
    name: 'Chevalier de Farmus',
    species: 'Human',
    source: StorySource.LN,
    hp: 240,
    damage: 28,
    defense: 12,
    speed: 150,
    knockback: 200,
    profile: PveProfile.AGGRESSIVE,
    tint: 0x37474f,
    width: 88,
    height: 120,
    asset: 'TODO_ASSET',
  },
  charybdis: {
    id: 'charybdis',
    name: 'Charybdis',
    species: 'Charybdis',
    source: StorySource.LN,
    hp: 980,
    damage: 38,
    defense: 16,
    speed: 90,
    knockback: 40,
    profile: PveProfile.BOSS,
    tint: 0x1565c0,
    width: 260,
    height: 200,
    asset: 'TODO_ASSET',
  },
  clayman_doll: {
    id: 'clayman_doll',
    name: 'Marionnette de Clayman',
    species: 'Doll',
    source: StorySource.LN,
    hp: 140,
    damage: 22,
    defense: 8,
    speed: 190,
    knockback: 150,
    profile: PveProfile.SWARM,
    tint: 0x6a1b9a,
    width: 64,
    height: 96,
    asset: 'TODO_ASSET',
  },
  clayman: {
    id: 'clayman',
    name: 'Clayman',
    species: 'Demon Lord',
    source: StorySource.LN,
    hp: 860,
    damage: 36,
    defense: 12,
    speed: 160,
    knockback: 90,
    profile: PveProfile.BOSS,
    tint: 0x4a148c,
    width: 120,
    height: 150,
    asset: 'TODO_ASSET',
  },
  ifrit: {
    id: 'ifrit',
    name: 'Ifrit',
    species: 'Ifrit',
    source: StorySource.LN,
    hp: 640,
    damage: 32,
    defense: 10,
    speed: 200,
    knockback: 160,
    profile: PveProfile.BOSS,
    tint: 0xff5722,
    width: 110,
    height: 140,
    asset: 'TODO_ASSET',
  },
}

export function enemyDef(id: string): PveEnemyDef | undefined {
  return PVE_ENEMIES[id]
}

export function biteAttack(def: PveEnemyDef): AttackData {
  return {
    id: `${def.id}_bite`,
    name: def.name,
    kind: AttackKind.MELEE,
    damage: def.damage,
    knockback: def.knockback,
    knockbackY: -40,
    stun: 0,
    hitstun: 10,
    energyGain: 0,
    energyCost: 0,
    startup: 4,
    active: 8,
    recovery: 18,
    hitWidth: def.width * 0.6,
    hitHeight: def.height,
    hitOffsetX: def.width * 0.35,
    hitOffsetY: -def.height * 0.2,
  }
}
